- src/pagination.js
Hey there, thanks a lot for this great work!
It seems there was a little typo preventing users from overriding the next/previous components. This PR fixes that. These properties are passed in lower-case to the component in `pagination.js`, but accessed in upper-case.
> Fix typo when overriding pagination components

- src/utils.js
This will allow the use of bound functions, which have a prototype of `undefined`. Fixes https://github.com/tannerlinsley/react-table/issues/109.
> use `Object.getPrototypeOf` instead of `.prototype`

- README.md
causes the accessors table to show up nicely on github's page - see my fork vs main 
Thanks for this component it is really good!
> Add extra empty line to README.md

- package.json
- yarn.lock
Removed `rm -rf` since it works on Linux environments.
Instead added **rimraf** npm package as it is supported in all environments even Windows.
> Updated the package.json - Issue #47

- src/index.js
Renames the sorting class names appropriately. Fixes https://github.com/tannerlinsley/react-table/issues/137
> Switch `-sort-asc` and `-sort-desc` in ternaries

- README.md
When I pasted your example into my project I got the following error:
`Uncaught Error: A column id is required if using a non-string accessor for column above.`
Adding an id to the `Friend Name` column fixed the error as the accessor is not a string.
After a bit of reading through your docs I worked out what the problem was, but thought as it's a quick fix I'll create a PR as well.
> Added an id to the Friend Name column in the example so it doesn't error

- README.md
Custom Cell Header Rendering link was broken in table of contents.
> fix broken TOC Link

- src/pagination.js
This fixes issue [169](https://github.com/tannerlinsley/react-table/issues/169)
* The top change asks if the new page is really a number before trying to use it (this avoids warning when typing two non-numeric characters) and return the current page otherwise
* The bottom change verifies that the current page is not the same as the new page
> Avoid page refresh if same page, set NaN to current page

- src/index.styl
Just a little fix. Now all the input tags except checkboxes and radios have their appearance set to none.
Was there any reason for resetting their appearance?
> Issue #14 (default CSS for checkboxes)

- .storybook/config.js
- README.md
- src/index.js
- stories/EditableTable.js
Would you consider adding `columnId` property to the `rowInfo` object? It would be very useful when referencing data in a table in a generic way. I've explained the rationale in the #237 as well.
> Add column id to the rowInfo object

- src/pagination.js
see the No Data in the example storybook. Pagination at the bottom shows 1 of 0 instead of 1 of 1.
https://react-table.js.org/?selectedKind=2.%20Demos&selectedStory=Custom%20%22No%20Data%22%20Text&full=0&down=0&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel
> when you have no data pages shows as 0 instead of 1

- src/methods.js
I just added a little change. As a column may be hidden, we must check it is not `undefined` before trying to access the `id` prop. This check was made in commit 6401786, but some changes made it appear a few lines after accessing the `id` prop in v6.0.0.
> Fixed issue #210 - Ignore filters on hidden columns.

- src/index.styl
This fix is for a IE bug regarding the select element. On IE, the default browser arrow was still being shown due to a appearance property bug.
> fix IE select visual bug

- docs/src/stories/ControlledTable.js
- src/index.js
- src/utils.js
This PR is related to issues described in #387
When a cell's maxWidth is NaN, the calculated style.maxWidth is `"NaNpx"`. React won't update the DOM's style when given this value, resulting in incorrectly sized columns.
This PR ensures the maxWidth style is properly handled when maxWidth is NaN.
Note this PR also will add a button to the Controlled Component story to allow the user to reset the controlled state.
> Max width NaN fix

- src/index.js
Pretty tiny tweak, but I presume this is the "expected behavior".
Currently, passing `resizable` will add or not add the resizing components (index L354). But the `'rt-resizable-header'` classname is always added.
This change will only add the `'rt-resizable-header'` if `resizable` is `true`.
Similarly on in child div inside the `<ThComponent>`.
> Use `isResizable` value in ThComponent classname

- README.md
In README's Fully Controlled Component section current filters model is assigned to `filters` property which does not work. It should be assigned to `filtered`.
> Fixed README's Fully Controlled Component filtered

- src/index.styl
This brings `rt-tfoot` into line with `rt-thead` in terms of flex behaviour.
Without this, it's possible for an `rt-tr` to be taller than its containing
`rt-tfoot` without causing it to expand, which causes the outer `rt-table` to
scroll vertically.
> make rt-tfoot flex behaviour the same as rt-thead

- src/index.styl
The current css selectors, eg. `.ReactTable input` cause conflicts with `input` elements inside Cells. So changed it to `.ReactTable .-pagination input`.
> Make the css for input and select more specific

- README.md
Parts of the README.md file had incorrect properties when talking about fully managed state. This just fixes those.
> readme-updated: Fixed incorrect property names

- README.md
We have found that with longer documentation files, the position of the sponsor link is more effective in helping fund the project when it's higher in the readme.
> Re-position code sponsor

- src/index.js
I needed my Cell functions to know what page/pageSize was being displayed (to do some custom numbering based on the current page) and couldn't find any way to access that info. This PR exposes those two items to the rows/cells.
> Expose page/pageSize to rows/cells

- README.md
- src/defaultProps.js
- src/methods.js
It's sometimes desirable to modify your sort method based on the direction of sort, for example in order to always sort null/undefined to the bottom of the table. This can be achieved simply by passing the direction of sort to the sort method, and doesn't change the default behaviour. The docs had a curious reference to "dir", which might have been intended for this, but the code doesn't reflect that.
> Supply sort direction to custom sort methods (#476)

- src/defaultProps.js
This PR fixes a bug where the `ThComponent's` base class comes after the configurable class name. This prevents a user from customizing the styling of the header without using `!important` in their CSS. The change allows for a custom header classname to extend the base styles.
> Fix ThComponent classnames ordering in defaultProps

- src/pagination.js
It's passed as `style`, not `paginationStyle`
https://github.com/react-tools/react-table/blob/master/src/index.js#L943
> Fix style prop not being properly used in ReactTablePagination component

- src/hoc/selectTable/index.js
The table select cell was hard coded to 30, it is now moved as prop and only defaulted to 30 => to be able to change it for each instance
> Move hard coded select width to prop

- src/defaultProps.js
This adds basic screen reader support to tables that are otherwise invisible to a screen reader. Ultimately I would like to add full accessibility support as described in WAI-ARIA 1.1 specifications.
> Implemented basic screen reader support.

- src/hoc/README.md
I ended up going thru the select table HOC source to figure out why non of my rows had a checkbox.  Turns out it assumes a default unique ID per row keyed as ._id and nothing mentions that at all.  So I figured I'd submit this in the hopes it can save someone else from having to do the same!  Let me know if you need anything changed or I just missed this being explained in the docs elsewhere.
> docs: add select HOC docs to better document how to use the HOC

- src/index.styl
Addresses #862 and an unreported issue I've been seeing in Chrome. Just seems like a saner default to me.
Compare:
Before
After
This is in Chrome on Linux (i3wm).
> Remove ellipsis from default expander table header

- README.md
Updating the `defaultSortMethod` in the README to match the [code](https://github.com/react-tools/react-table/blob/3a8a037ee68b11e329c581a8d61a37db276a0dbf/src/defaultProps.js#L46)
> Fix README: `defaultSortMethod` doesn't match code

- README.md
I found mismatched names of parameters passed to onFilteredChanged prop in docs.
It was supposed to be "(filtered, column)", not "(column, value)".
Simple typo corrected on README.MD.
> Just correct names of parameters for onFilteredChanged

- README.md
I think this is the most common way of setting columns or expanderDefaults.
I had to find issue #565 and then follow it to issue #394 to see explanations on how to do this.
> Add more documentation for overriding props

- src/hoc/README.md
The documentation has some code blocks that are broken here: https://react-table.js.org/#/story/hoc-readme
I've added a line break that I believe will fix it, and also fixed a typo.
> documentation formatting fix

- src/propTypes.js
The prop type for `getFooterProps` is currently `PropTypes.object`, but `getFooterProps` (like all of the other `getXProps` props) should be a function. Providing a function for this prop works as expected but throws a PropType validation error.
This change updates the type to `PropTypes.func` to match the other `getXProps` props.
> Fix propTypes validation for getFooterProps

- src/hoc/treeTable/index.js
- src/index.js
This should allow people using the `treeTableHOC` to use an `id` instead of an `accessor` to reference the pivoted field.
Also, it seems to me that an expandable cell should never be hidden.  The `treeTableHOC` code adds a `show: false` to both the subrows _and_ the expandable rows.  Not sure where I'm enforcing that was the right place, but it seems to be the issue experienced by these users:
https://github.com/react-tools/react-table/issues/891
https://github.com/react-tools/react-table/issues/930
> Tree uses accessor or ID and always shows pivot cells

- src/hoc/selectTable/index.js
Fix for [#1020](https://github.com/react-tools/react-table/issues/1020)
> SelectTable - Make input component type defaults to checkbox

- src/hoc/treeTable/index.js
Pass Expander, PivotValue and Pivot renderers to column builder in TreeTable HOC.
> Add additional column's renderers in TreeTable HOC

- src/index.js
- yarn.lock
I was having issues using `getTfootProps` to accept my extra props. And then I checked the source and noticed the issue was `_.splitProps` was not being used on `getTfootProps` in `makeColumnFooters`, yet line 783 clearly was attempting to use `.rest` from what would have been the result of `_.splitProps`. This fixes the bug.
> Allow rest props from getTfootProps for TfootComponent

- package.json
`react-table` uses `prop-types` in its source and hence including it as a peer dependency makes sense. Also, this helps analysis tools like bundlephobia.com determine external packages.
> Adds "prop-types" as a peerDependency

- src/utils.js
Given a class component as a Renderer or Filter, react-table throws an error `TypeError: Cannot call a class as a function` instead of rendering the component. This appears to be because the util is using `isReactComponent` to check whether an object is a component, which I believe was an implementation detail from the old `React.createClass` days and isn't defined in modern class components.
Renderers: (`{ Cell: MyCell }`)
```jsx
// functional component, works
const MyCell = props => props.value
// class component, throws
class MyCell extends React.Component { 
render() {
return this.props.value
}
}
```
Filters: (`{ Filter: MyFilter }`)
```jsx
// works
const MyFilter = ({ filter, onChange }) => (
<input 
value={filter ? filter.value : ''} 
onChange={e => onChange(e.target.value)} 
/>
) …
```
> Resolves TypeError when rendering class components Renderers and Filters 

- src/pagination.js
Had some issues using the pagination component as the page number would always reset in response to any prop change
> Bugfix: Pagination component: Only update page state if page prop actually changes

- src/hoc/selectTable/index.js
Changed defaultProps.selectType from "check" to "checkbox".
While working with react-table for my first time (aiming to replace an overly-complicated table solution at work), I found that by default the selectTable HOC component gave me an input for the checkbox, which I found to be quite odd.
Here is a screenshot and a CodeSandbox demonstrating how I ran into this issue:
https://codesandbox.io/s/z3ylko96pp
I found that defaultProps.selectType (on the selectTable HOC) was set to "check", which is an invalid value to be passed to an `<input>` element in the `type` attribute. I changed it to "checkbox" in this PR.
Here is a screenshot using the correct "checkbox" value:
Let me know if "check" and the text-input behavior was intended. :+1:
> Fixed defaultProps.selectType.

- src/defaultProps.js
- src/methods.js
- src/propTypes.js
This PR implements the `minResize`-Prop which specifies to what minimum width a column can be resized.
I found [this](https://github.com/react-tools/react-table/issues/536#issuecomment-334904841) issue where @gary-menzel mentions something like this. I found this after I added the functionality.
Please review this PR and suggest changes. As of now the functionality is in place and satisfying my current needs. I would like to see this in the main repo otherwise I will have to use my fork from now on.
> feature: allow minResizeWidth to be set

- README.md
I found the added Props by looking into the defaultProps.js when I could not find a way change the styling of the filter row.
Custom Props
Built-in Components
Every single built-in component's props can be dynamically extended using any one of these prop-callbacks:
<ReactTable
getProps={fn}
getTableProps={fn}
getTheadGroupProps={fn}
getTheadGroupTrProps={fn}
getTheadGroupThProps={fn}
getTheadProps={fn}
getTheadTrProps={fn}
getTheadThProps={fn}
+getTheadFilterProps={fn}
+getTheadFilterTrProps={fn}
+getTheadFilterThProps={fn}
> Updated ReadMe with some more Props

- README.md
Javascript has no implicit return. Needs the statement. Added it to the example.
> Example code fixed with missing return statement

- src/hoc/README.md
Also fixes up some language and remove other import instructions. It's better to just have the import instructions in just one place.
> Adds import instructions to the HOC README

- README.md
- src/pagination.js
Pagination elements are now customizable without having to create a new `Pagination` component, that would mostly mimic the existing one in terms of functionality.
I have updated the README to include the newly added props.
> Extract pagination elements renderers to pagination props

- src/hoc/selectTable/index.js
This is a small change to add an 'aria-label' attribute to each checkbox in selectTable HOC. Text of label is dynamically generated from other row props.
> Adds aria-label prop to checkboxes

- src/methods.js
Fixes #1230 -- needs review.
When firing fetch data, react-table needs to send the current values for `page`, `pageSize`, and `filter` (and perhaps other values as well but these were the most obvious. For manual tables, when setting state in the handler for `onFetchData`, the end user needs to pass the props back to the react-table instance in order to keep everything in sync.
> update fireFetchData to use current state for select value

- src/index.js
- src/methods.js
- src/utils.js
Support for recursive Header Groups
Feel it is important functionality that is currently missing in current version and I really need it for project I am working on
- Applied the patch https://github.com/react-tools/react-table/pull/1077.patch
- Update `Array.concat` references to `[].concat`
The following lint errors exist on master prior to applying any changes
```
~/react-table/src/index.js
669:17  error  'newExpanded' is assigned a value but never used  no-unused-vars
670:46  error  'cellInfo' is not defined                         no-undef
~/react-table/src/methods.js
621:83  error  Extra semicolon  semi
622:98  error  Extra semicolon  semi
~/react-table/src/propTypes.js
121:33  error  Missing trailing comma  comma-dangle
130:28  error  Missing trailing comma  comma-dangle
168:76 …
```
> Support Recursive Column groups

- .travis.yml
We should use node version 10 since it's the active LTS until 2021-04-01. See [Node.js Releases](https://nodejs.org/en/about/releases/) for more info.
This should also fix the TravisCI builds.
> TravisCI: Use node version 10 (fixes TravisCI builds)

- .travis.yml
Cache yarn files like it is recommended by [TravisCI docs](https://docs.travis-ci.com/user/caching/#yarn-cache) for a faster build time.
> TravisCI: Cache yarn files

- README.md
The travis ci badge points to the wrong url and does not specify the branch
> TravisCI badge: Use correct link

- src/index.js
Pass complete row information to onExpandedChange handler.
In response to this:
https://github.com/tannerlinsley/react-table/issues/1201
> Fixes/pass cell info to onExpandedChange handler

- src/hooks/useSortBy.js
V7 adds the option to remove a sort option, so it goes from asc -> desc
-> unset, then repeats.  V6 just went from asc -> desc then repeated.
Personally I much preferred this, I think that there's a case to be made
that this is the more expected behavior.
I'm not sure if this is really the best way to fix this since it adds
yet another api option and I completely understand that that is less
than desirable, but I also would rather add an option than have to
duplicate the whole useSortBy hook.
> Provide option to toggle sort like V6

- package.json
- rollup.config.js
Hi Tanner,
Here is a PR that provides an ESM build to the tools that support it.
For example Webpack now uses the `.es` version of the library instead of the umd one, making things lighter.
Hope this helps,
> Add support for es module build

- src/hooks/useExpanded.js
Hey guys,
Here is a PR that fixes `useExpanded` that was not usable at the moment. The reason is that all the `subRows` were flattened at the root level. Which was breaking the `usePagination` component.
Now the rows are correctly nested and pagination works fine.
What is did is the following:
**Before**
```
[
{ id: 'row-0' }
{ id: 'row-0-0' }
{ id: 'row-1' }
{ id: 'row-2' }
{ id: 'row-3' }
]
```
**After**
```
[
{ 
id: 'row-0', 
subRows: [
{ id: 'row-0-0' } 
] 
}
{ id: 'row-1' }
{ id: 'row-2' }
{ id: 'row-3' }
]
```
Please see the following code sandbox with a working example: https://codesandbox.io/s/react-table-v7-sandbox-8wr0e
> Fix useExpanded wrongly flattening subRows

- src/hooks/usePagination.js
To be honest I'm not sure what this useLayoutEffect is there to do.
It has no visible effect if you don't use manualPagination, and if you
do it, simply jumps you back to the first page, defeating the point of
you having control of the pagination.
> Fix pagination resetting to page zero with manualPagination

- src/hooks/useTable.js
Added undefined to` unspecific getRowProps`  fn because `api` param replaces the context of `row`.
See this ticket for more info:  https://github.com/tannerlinsley/react-table/issues/1388
> getRowProps preserve param order

- src/hooks/useColumns.js
- src/hooks/useFlexLayout.js
The grouped header columns are not adjusting width if child columns update their `show` property.  This is because the Headers are basing their width on the sum of the child columns, but not factoring in the `show` property.
You can see an example below.  I added a button to toggle the fix on and off.
https://codesandbox.io/s/react-table-v7-sandbox-2qyr4
> Fixed grouped column Header that were not adjusting based on hidden child columns

- README.md
- src/index.js
The documentation mentions a [`getTfootThProps` prop](https://github.com/tannerlinsley/react-table/tree/v6#props) but it does not exist in the code anywhere. Instead there is the `getTfootTdProps` prop. So I corrected that in the docs.
Also, I noticed that `getTfootTdProps` is missing the `column` argument. All other similar functions in that scope (as well as the `getTheadThProps`) do have it. So I added it. This also (partially) fixes #1120.
> [v6] getTfootTdProps

- README.md
in commit ea79cd838891a21db6754c387a73d3ea4fffd127 the`getRowProps` member of the headerGroup object changed into `getHeaderGroupProps`
The example in readme still referenced the old `getRowProps`, I think this should be updated to `getHeaderGroupProps`.
> Small readme example update

- src/utils.js
Just a small improvement leveraging default parameter instead of `typeof`
> fix(utils): default Cell renderer cleanup

- README.md
- src/plugin-hooks/useSortBy.js
1. Provide configuration for multisort that pressing shift key is not compulsory
2. Configurable limit on max number of columns for multisort, like configuration has been provided that `maxMultiSortColCount` is 3, suppose currenlty table is sorted by `[A, B, C]` and then clicking `D` for sorting should result in table sorted by `[B, C , D]`
> [v7] useSort - Multisort functionality: Limit max cols and optional shift key

- src/hooks/useTable.js
in case of using construction like:
```javascript
{
defaultColumn = {}
}
```
`defaultColumn` will get new instance each time, so as result it force to recalculation each of `React.useMemo`.
> improve(use-table): use single instance of defaultColumn property

- src/plugin-hooks/useFilters.js
- src/plugin-hooks/useSortBy.js
I have a table that dynamically generates columns (there is a switch that transposes rows to columns and vice versa). However if I sort the existing table and then click that "switch" button, I'm getting error `Cannot read property 'sortType' of undefined`, because the column by which the content was sorted before no longer exists. This PR fixes this issue - if the column no longer exists, the sorting function for it always returns 0 (so the items stay in its original place). I don't remove them from `sortBy` state, because, as I said, my table has a switch, so if I go back to previous view it will keep the sorting that I set before switching. It works the same way with filters, so I think it's fine.
By the way, I'd recommend installing Prettier as dev dependency instead of relying on …
> fix(use-sort-by): sorting now ignores column ids that no longer exist

- src/plugin-hooks/tests/__snapshots__/useRowSelect.test.js.snap
- src/plugin-hooks/tests/useRowSelect.test.js
- src/plugin-hooks/useRowSelect.js
Selecting a row that has subRows will now also select the subRows. It makes sense to select subRows if the parent row is selected but this functionality may not be desired for react-table.
Parent rows are also updated according to the subRows selection.
Let me know if any optimisations can be made.
> Sub rows are selected if the parent row is selected.

- src/index.styl
Replace outline: none with outline-width: 0 to allow reset of outline styles to default browser settings. Closes #1471
> fix: replace 'outline: none' with 'outline-width: 0'

- docs/api.md
This fixes an error in the documentation for `useSortBy`, where it says columns will have `sorted` and `sortedDesc` fields to denote sort state. The current implementation, however, uses `isSorted` and `isSortedDesc` as the field names: https://github.com/tannerlinsley/react-table/blob/4537f28a8d3b304b03fa6bd752fb99025130573d/src/plugin-hooks/useSortBy.js#L202-L204.
> fix field names in useSortBy docs

- src/hoc/advancedExpandTable/index.js
- src/hoc/foldableTable/index.js
- src/lifecycle.js
- src/pagination.js
React 16.9.0(and upwards) deprecated usage of `componentWillMount` and `componentWillReceiveProps`.
This pr renames the methods to use the renamed UNSAFE ones. It suppresses the warnings. As you guys have decided to not continue working on v6, I guess this is the best we can do.
Edit: I've seen you guys still support React 15.x in package.json. Can we drop the support and only support React v16? This would make this fix much easier.
> Fixing react warnings

- src/utils.js
This fixes an issue using arrow functions for custom `Cell`s introduced in the latest release 
Issue: #1502
> use getPrototypeOf instead of .prototype

- src/plugin-hooks/useRowSelect.js
When using the useRowSelect hook if you had no rows in the table `isAllRowsSelected` would be `true` as the number of selected rows equals the number of rows and a checkbox will be checked. This shouldn't be the case. You can preview the issue [here](https://codesandbox.io/s/tannerlinsleyreact-table-row-selection-qizrj).
This is just a simple fix for that issue.
> isAllRowsSelected can only be true if there are rows.

- index.d.ts
I've found that trying to get solid TypeScript typings for this library
are a bit of a challenge.  The composable nature of the library means
that the types for the builtin functions are by their nature somewhat
minimal, and that the user needs to be able to extend those interfaces
to reflect the specific plugins that are in use.
With that in mind I propose something like this.
To get the best out of them, you then need to extend those interfaces
using declaration merging, see
https://www.typescriptlang.org/docs/handbook/declaration-merging.html
e.g.
```ts
declare module 'react-table' {
export interface TableInstance<D = any>
extends UseFiltersValues<D>,
UsePaginationValues<D>,
UseExpandedValues,
UseGroupByValues {}
export interface TableState<D = any>
extends UsePaginationState, …
```
> TypeScript updates

- package-lock.json
- src/hoc/advancedExpandTable/index.js
- src/hoc/foldableTable/index.js
- src/lifecycle.js
- src/pagination.js
- src/utils.js
hi @tannerlinsley  - thanks for your great work on this fantastic table component lib.
we recently upgraded our app to 16.9 and noticed the lifecycle deprecation warnings - we look forward to upgrading our tables to v7 however before it is production ready we'd like to eliminate those deprecated methods from the app so here's my attempt to fix them.
I didn't find any test suites in the repo - however I did test the changes locally in our app and didn't notice any issues. However we don't really utilize the full potential of `react-table` please let me know if there is a better way to test the changes.
> fixes deprecated lifecycle method warnings in v6

- docs/api.md
- package-lock.json
- package.json
- src/plugin-hooks/useExpanded.js
- src/plugin-hooks/usePagination.js
- src/utils.js
Added useExpanded 'expandSubRows' option
- Allows consumer to opt out of adding subrows to regular rows when expanding
- Also updated usePagination to respect this flag
- Updated README
> feat(useexpanded, usepagination): omit subRows from rows

- src/utils.js
`Object.getPrototypeOf(component)` returns React `Component()` function itself, not a prototype of `Component` but `isReactComponent` is a property of `Component.prototype`.
So correct check here is `Component.prototype.isReactComponent` not `Component.isReactComponent`.
> Fix isClassComponent function

- .travis.yml
- package-lock.json
- package.json
- yarn.lock
Test on Node.js 10 and 12, long term release support versions.
Test on Linux, Mac, and Windows machines.
> ci: test cross platform

- TYPESCRIPT.md
- react-table-config.d.ts
This is tied to the type implementation found in https://github.com/tannerlinsley/react-table/pull/1535.
I'm more than happy if this gets merged into that branch before merging, or whatever's convenient :)
> Add typescript docs

- README.md
- index.d.ts
- package-lock.json
- package.json
This is a PR to the `v6` branch, following the discussion in the #1576.
What it does:
1. Changes the package name inside the `package.json` (and ups the version to 6.11.0, if you'd want to change the name as a part of publishing process — tell me, I'll roll it back).
2. Adds all the appropriate changes to the README.md, adding a few notes on the state of this version.
3. Adds an `index.d.ts` file containing the type definitions from the `@types/react-table`. This is needed in order for TypeScript to use proper types as this would be a package with a different name from the one in the DefinitelyTyped project. And I think that keeping typings closer to the code is better in case we'd need to adjust them anyway. This can be discussed of course.
> Changing the name to react-table-v6

- index.d.ts
- tslint.json
re-enables dtslint array type rule
> refactor: update complex types to use Array<> syntax

- docs/api.md
- src/plugin-hooks/useGroupBy.js
unlike other hooks, the column.disableGrouping actually enabled grouping for a column
> fix(usegroupby): column.disableGrouping inverted logic

- TYPESCRIPT.md
- index.d.ts
Missed `selectedFlatRows` on the `useRowSelect` plugin types.
Cleaned up a bit of wording in the Typescript docs
> Add selectedFlatRows to typings

- index.d.ts
These definitions mask errors in the other definitions and there are better
ways of extending these.
See https://github.com/tannerlinsley/react-table/pull/1597 for an
example of an existing prototype that was missing but harder to find
because of these definitions.
> remove Record from HeaderProps and CellProps

- package.json
- rollup.config.js
- src/propTypes.js
- src/utils.js
We have been using v6.10.0 and one of our cell components was changed to use `React.memo` and the table unexpectedly stopped working. It looks like other have users reported issues with `normalizeComponent` in various versions and some fixes have been made. 
Unfortunately some users have code that assumes the "components" are just a element factory and not a true React component. When these React components are defined inline this can cause  unmounts when the parent component is re-rendered. This branch will not fix that issue but I think instead users should avoid creating inline components and just use React context if you absolutely need to provide anything to these components.
The fix for us was to use `isValidElementType` from `react-is` for component detection and allow us to use …
> v6: prefer components in normalizeComponent

- index.d.ts
* There it was, on an unused UseGroupByHeaderProps interface, while it should have been on UseGroupByColumnProps.
> Types: getGroupByToggleProps was lost

- src/plugin-hooks/usePagination.js
Fixes #1657 
[Discussion at spectrum](https://spectrum.chat/react-table/general/v7-maximum-update-depth-exceeded-usegroupby-useexpanded-with-usepagination~2c25e2b8-7a61-4c32-84b3-87db458701c2)
Thanks to @iamjon for identifying usePagination was the culprit.
I then checked the last changes made to it, and noticed it was previously listening to data and now it listened to rows (which I believe is a new reference on each render), causing infinite loop on one of its effects.
I tested this change on my project and everything seems ok now.
> [Fix] defaultGetResetPageDeps should listen to data, not rows

- index.d.ts
Fixes #1628 
- These 2 methods receive the original row object (`<D>`)
- getSubRows returns an array of original rows (`Array<D>`)
- Changed return type of getRowID to match type of Row.path (`Array<IdType<D>>`)
- **_[Please confirm]_** Removed getSubRows from UseExpandedOptions as it doesn't appear to be used.
> Fix types of getRowID & getSubRows

- .github/size-plugin.yml
- package.json
- rollup.config.js
- yarn.lock
> setup size-plugin-bot

- .size-snapshot.json
- src/plugin-hooks/useSortBy.js
`resetSortBy` changes the `state.sortBy` property from an array to an object, causing a crash at https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/useSortBy.js#L252 when my project reloads via HMR.
> fix: fix crash in useSortBy resetSortBy action

- .gitignore
- src/lifecycle.js
I think this is the piece that is causing https://github.com/tannerlinsley/react-table/issues/1686 
tested locally (in a sandbox app) and it fixed the issue for me.
my apologizes to anyone that has been affected by this 😭
I played with it a little bit and haven't found a way to get rid of `UNSAFE_componentWillMount` completely, for now let's just add it back here. I will come back and try to get a better understanding of the codebase. 
by the way @tannerlinsley  if you could give us some directions about how to test this repo thoroughly that'd be wonderful. without unit tests I'm not very confident in making big changes. thanks!
> [v6] fixes broken lifecycle.js

- examples/material-UI-components/src/App.js
In the Material UI example, I found `getTableHeaderProps` was declared as a property returned by the root `useTable` hook. This was confusing since this function is not part of the table instance properties API or in the documentation.
> Remove unused property destructured from useTable example

- src/plugin-hooks/useFilters.js
- src/plugin-hooks/useSortBy.js
I want to use the getResetFiltersDeps to detect the state for resetting the filters. I want to reset the filters, when the user deletes all filtered items. So I must check the instance rows length to be 0. But the instance.row param on the getResetFiltersDeps function lags one render behinde. To fix this i moved the effect function at the end of the useFilter function and pass the updated row into the instance param.
I tought that this fix could by applyed to other use functions (sort, pagination, etc.)
> [getResetDeps] fix instance param lag

- src/plugin-hooks/tests/__snapshots__/useSortBy.test.js.snap
- src/plugin-hooks/useSortBy.js
When sorting is disabled there is no onClick on this column, so we also did not need the tooltip.
> Remove tooltip if columnDisableSortBy

- .size-snapshot.json
- docs/api/README.md
In the /docs/api/README.md the useTable link was linking to the file ./usetable.md that doesn't
exist, now it links to ./useTable
> docs(docs/api/readme.md): fix to useTable link that was giving 404

- src/plugin-hooks/useExpanded.js
The wrong variable was being checked against `undefined`, so the row was always being toggled, rather than taking the parameter into account.
> Fix row.toggleExpanded(bool)

- src/utils.js
User should be able to pass render components wrapped by `React.memo` and `React.forwardRef` in column definitions.
Though `React.forwardRef` is not so valid here since the render function will only pass the props to the render, I think it should be safely included.
See the bugged example: https://codesandbox.io/s/fervent-night-6v86g, which should be fixed by this pr.
> fix: render components should include memo/forwardRef

- examples/sub-components/src/App.js
Addresses issue #1780 , fixing the React console warning for the "Sub-Components" regarding the lack of unique key for each child in list.
Replaces `<>` with `<React.Fragment>`, spreading the row props onto the fragment.
> Update to use React.Fragment spread with row props

- .size-snapshot.json
- src/plugin-hooks/tests/useGroupBy.test.js
- src/plugin-hooks/useGroupBy.js
Turns out it's super easy to simulate the error by setting the initial state with a group-by column that doesn't exist, so I just modified the existing test to contain that.
> Fix groupBy removed columns (#1776)

- src/plugin-hooks/useSortBy.js
Added sort order as parameter for calling sortMethod(will be useful to provide more control in custom sortMethod)
Example :- To keep empty strings at bottom when sort in asc/desc order.
```
function stringSort(rowA, rowB, columnID, desc) {
let a = getRowValueByColumnID(rowA, columnID);
let b = getRowValueByColumnID(rowB, columnID);
return compareBasic(a, b, desc);
}
function compareBasic(a, b, desc) {
if (a === b) {
return 0;
}
if (a === '') {
return desc ? -1 : 1;
}
if (b === '') {
return desc ? 1 : -1;
}
return a > b ? 1 : -1;
}
```
> [useSort] Add sort order custom sortMethod

- .size-snapshot.json
- src/plugin-hooks/useFilters.js
Fix to correctly alias filterTypes to userFilterTypes in set filter action, so that the filter
autoremove method is called correctly
fix #1831
> fix(usefilters): fix userFilterTypes alias in setFilter action

- docs/concepts.md
This is a very small and opinionated suggestion regarding the «Concept» section of the docs.
Just link to the original blog post and ditch Medium, especially given the fact that you already have it online somewhere else. I really don't care about their business model, but in terms of UX/UI Medium is an abomination. I tried to read the thing on my mobile on a train ride earlier today. Ugh.
Then I found the link at the top (I know, right) that points to the original post – much cleaner, no more fighting modals and whatever shitshow is going on over there – I mean, just *readable* fcs. 
I might be unaware of some advantages you see by promoting Medium over your own, imho much better approach. If there are any, just don't mind me. 
Thanks for the project and have a nice weekend!
Regards
Lukas …
> docs: link to the original blog post instead of medium

- src/plugin-hooks/useFilters.js
- src/utils.js
To auto remove `filters` using `autoRemove` fn on `ColumnFilter`, there may be some use-cases which require `Column` metadata to be available for making decisions.
> Add `Column` data in `autoRemove` of Filters

- examples/kitchen-sink-controlled/src/App.js
There's an error on this page that says `useGroupBy` must come after `useFilters`
> Fix code sandbox for kitchen sink

- .size-snapshot.json
- src/plugin-hooks/useRowSelect.js
The `shouldExist` is enough to check if we should add or remove a row from the list of selected rows: 
https://github.com/tannerlinsley/react-table/blob/10a5a9226027149004ffed7cf3d3dd26b41afbac/src/plugin-hooks/useRowSelect.js#L125-L127
And for the case when the value is the same as before, we already return from the function: 
https://github.com/tannerlinsley/react-table/blob/10a5a9226027149004ffed7cf3d3dd26b41afbac/src/plugin-hooks/useRowSelect.js#L129-L131
I had an issue where for some reasons my table had `undefined` for the `isSelected` there, but couldn't reproduce it on CodeSandbox. This issue seemed to impact only these conditions, making selected rows not uncheckable, removing this unnecessary check fixes it for me.
If someone knows why the `isSelected` can be `undefined` in the …
> useRowSelect: remove redundant checks

- .size-snapshot.json
- src/hooks/useTable.js
When the headerGroups were defined at first, they were memoized and then attached to `getInstance()`, but later `getInstance().headerGroups` was redefined using a filter, removing the memoizing.
That PR fixes it by properly memoizing the new filtered `headerGroups`.
[Diff without whitespace changes](https://github.com/tannerlinsley/react-table/pull/1920/files?utf8=%E2%9C%93&diff=split&w=1)
> useTable: Fixes memoizing of headerGroups

- docs/api/useTable.md
Adds additional context on `accessor` field for column options.
https://github.com/tannerlinsley/react-table/issues/1927
> Add additional info for accessor docs

- src/hooks/useTable.js
One of the more recent fixes (https://github.com/tannerlinsley/react-table/commit/42b41d1260fab3c6635b071ca984dce253bf23ab#diff-58070e993396b86d9cd977598221d49eR241-R251) broke some of the stuff with the visibleColumns.
Basically, previously after all the `vislbleColumns` hooks they were retroactively added back to `allColumns`. The new way without deduping is mistakenly prioritizes columns from the `allColumns`, not overwriting them with those from the `visibleColumns`.
In this PR I just changed it so the new `allColumns` would be `visibleColumns` first and then it only those columns not present in the `visibleColumns` would be pushed, which seems like what was intended.
I've tested this fix on my project (which broke after upgrading to the 7.0.0 release) with a yarn's `portal:`, and it …
> Fix combining the new visible columns with all

- docs/faq.md
This change updates the example to replace an undeclared variable with the usage of `skipPageResetRef`. I was reading through this docs page today and believe this is the correct usage of `React.useRef()` in the context of this example.
> Update autoReset FAQ docs example

- docs/installation.md
- package.json
- yarn.lock
This change adds a `devDependency` on Scarf for installation analytics to support the maintainers of React Table. 
Discussion from everyone is welcome! Some background on the library and the problem it's solving can be found in this post here: [https://github.com/scarf-sh/scarf-js/blob/master/WHY.org](https://github.com/scarf-sh/scarf-js/blob/master/WHY.org). The package README ([https://github.com/scarf-sh/scarf-js](https://github.com/scarf-sh/scarf-js)) has more info on exactly what data is sent on each install. 
The analytics introduced here are opt-out by default, so data will only be collected from users who explicitly enable it. Because it has been added as a `devDependency`, it also won't be triggered during production builds that depend on `react-table`.
The data Scarf collects …
> Add dependency on Scarf for installation analytics

- docs/api/useTable.md
- examples/editable-data/src/App.js
- examples/grouping-column/src/App.js
- examples/grouping/src/App.js
- examples/kitchen-sink-controlled/src/App.js
- examples/kitchen-sink/src/App.js
- examples/material-UI-enhanced-table/src/components/EnhancedTable.js
- examples/pivoting/src/App.js
- src/hooks/useTable.js
- src/plugin-hooks/tests/useAbsoluteLayout.test.js
- src/plugin-hooks/tests/useBlockLayout.test.js
- src/plugin-hooks/tests/useFilters.test.js
- src/plugin-hooks/tests/useFiltersAndRowSelect.test.js
- src/plugin-hooks/tests/useFlexLayout.test.js
- src/plugin-hooks/tests/useGroupBy.test.js
- src/plugin-hooks/tests/useSortBy.test.js
- src/publicUtils.js
One thing that I wondered about and wasn't sure why it was changed from v6 to v7 is the Cell renderer API, where the value was only accessible inside the `cell`. From how I look at it, nothing stops us from returning it back, as there shouldn't be any collisions with the instance's properties and methods, and it would make both migrating from v6 much easier, and writing new Cell code much simpler as well.
We can still keep `cell` for stuff like in the `useRowState` and not to break anything for those who already use the v7's API.
If there was a reason to remove the `value` from the Cell's props, I'd be happy to talk about this in order to find a better solution for the underlying problem.
> Add cell’s value to its renderer back

- package.json
- yarn.lock
Relates to #2013 
This PR moves docz-related dependencies to the package.json's devDependencies block.
I recently upgraded to the latest version of react-table and found that gatsby and its related dependencies were added to my project's yarn.lock file. By moving docz to devDependencies, installers of the react-table package will not have to download gatsby etc. into their node_modules and yarn.lock file.
> fix: move docz to devDependencies

- package.json
Fixes #2082.
- Include `scripts/` in `npm` tarball so `postinstall` script does not fail for users.
- Remove `LICENCE` and `package.json` entries from `"files"` since they are [always added by default](https://docs.npmjs.com/files/package.json#files).
> Add `scripts/` dir to package `"files"`

- docs/api/useFilters.md
- docs/api/useGlobalFilter.md
- docs/api/useRowSelect.md
- docs/api/useRowState.md
I noticed that I couldn't find `how-do-i-stop-my-table-state-from-automatically-resetting-when-my-data-changes)` while going through the docs. After running the docs locally, some links to this page were returning 404s.
I have fixed the broken links and noticed that `api/useFilters` was updated a couple of weeks ago (https://github.com/tannerlinsley/react-table/pull/2067). For consistency, that one has been updated as well so that all faq links point to `/faq#id`.
> fix: Docs | Fix broken links to FAQ 

- package.json
- yarn.lock
This change is just the dependency version bump for scarf. It's needed in order to actually pull down the fix that will resolve things for #2169. 
Some improvements went into the newest scarf version beyond this bugfix, so we bumped the minor version going from `0.1.5` to `0.2.0`. I expected this change to be pushed to react-table users, as it was pinned to `^0.1.5`, and this is a backwards-compatible change. I didn't realize that npm actually treats <1.0.0 versions a bit different when it comes to the caret (https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004). So react-table is currently only getting updates for scarf `<0.2` right now. With this update, it will be on the new `1.0.4` release, which happens to be identical to `0.2.0`. The next breaking change, if ever, will bring …
> Update @scarf/scarf version to ^1.0.4

- docs/api/useTable.md
was removed in 7.0.0-rc.2 according to the changelog
> docs: remove debug from table options

- docs/examples/simple.mdx
Wrong url of CodeSandbox for Expanding example
> fix: Expanding example

- examples/filtering/src/App.js
When filtering large grids (or the browser runs on a slow computer),
typing in the search box can lack a bit of feedback, as the search box
is only updated with the characters the user types together with the
filtered table.
It took me a small while to figure out how to correctly use
useAsyncDebounce and useState to debounce the onChange event handler, so
I thought it might be useful in the filtering example.
> Add useAsyncDebounce to filtering example

- .github/workflows/links-test.yml
This will help in early detecting/avoiding broken links of docs and examples. And can help us avoiding fixes/work like https://github.com/tannerlinsley/react-table/pull/2277
> chore: Add github action to detect broken links in readmes

- README.md
I got an error from gatsby-plugin-mdx because of the closing li tags
```
"gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:
unknown: Expected corresponding JSX closing tag for <ul> (155:42)
153 | <p><a parentName="p" {...{"href":"https://github.com/sponsors/tannerlinsley"}}><img parentName="a" {...{"src":"https://raw.githubusercontent.com/tannerlinsley/files/master/sponsorships/supporters.png","alt":"Supporters"}}></img></a></p>
154 | <ul>
> 155 | <li parentName="ul">{`Jon Eickmeier`}</li></li>
SyntaxError: unknown: Expected corresponding JSX closing tag for <ul> (155:42)
```
> docs(readme): remove unnecessary li closing tags

- examples/bootstrap-UI-components/README.md
- examples/bootstrap-UI-components/src/App.js
Bootstrap UI example has an incorrect example URL and was using TH's for the table rows
> Fix bootstrap ui example

- src/plugin-hooks/useResizeColumns.js
- src/utils.js
This fixes #2302 and brings IE support to the useResizeColumns plugin. It adds a feature check function which performs a memoized check for using `{ passive: false }` in an event handler.
It seems that with IE 11, the event could be added with the unsupported option, but then the event could never be removed. This caused a move handler to be added on every mousedown on a resizer, and the rezising would never stop.
More info on the feature check:
- https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Safely_detecting_option_support
- https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
> fix: detect browser support for passive events

- src/filterTypes.js
This is sort of a fix for #2174.
In a recent release, #2001 changed the behavior of the `includes` filter to check for a single filter value within an array or string row value. This broke some existing usages of the previous `includes` filter, which expected the previous behavior (checking for a single row value within an array or string filter value).
`includes` is a very vague name/name-prefix to begin with (especially without any documentation yet around built-in filterTypes), but I expect that the new behavior is probably a more common use-case, especially scenarios where the row value is a string. From what I've seen, most of the codesandbox examples expect this behavior too.
So, instead of reverting #2001, I think it makes more sense to add a new filter to reintroduce the previous …
> Feature/Fix: Add filterTypes: includesSome & includesValue

- docs/api/useAbsoluteLayout.md
- docs/api/useBlockLayout.md
- docs/api/useFlexLayout.md
- src/plugin-hooks/useAbsoluteLayout.js
- src/plugin-hooks/useBlockLayout.js
- src/plugin-hooks/useFlexLayout.js
This PR adds support for footers to `useBlockLayout`, `useFlexLayout`, and `useAbsoluteLayout`, and updates the docs for these plugins to mention the `getFooterGroupProps` and `getFooterProps` prop getters.
> fix(layout plugins): add support for footers in layout plugins

- src/hooks/useTable.js
Adding initial rows property, which helps in getting rows before sorting, filtering etc.
> feat: add initialRows property on instance

- src/aggregations.js
Update syntax in return line of unique aggregation function
Use Array.from() instead of the spread operator [...]
Motivation: prevent polyfilling to [].concat() to enable reference by string in column definitions
closes #2173
> fix(aggregations): update syntax in unique aggregation function

- docs/src/manifests/manifest.json
The links for `material-ui` and `material-ui-kitchen-sink` in the docs are broken and throw a 404. 
The path has an uppercase `UI` term in the path. This PR changes it to lowercase so the links work as expected
> docs: fix material ui examples links

- docs/src/components/LayoutDocs.js
this PR addresses the same issue. 
https://github.com/tannerlinsley/react-query/pull/733#issue-447454853
> fix: docsearch is rendered twice with keyboard shortcuts

- examples/sorting/README.md
The link to the API documentation went to a 404, so I switched it to where the API documentation is currently located.
> Fix dead link in readme

- docs/src/pages/docs/quick-start.md
``quick-start.md`` uses "Gettin your data" which contains a typo for the word "getting."
This PR changes "Gettin" to "Getting" in the Quick Start.
> docs: fix typo in quick start

- docs/src/pages/docs/api/useSortBy.md
Docs: Add additional sortBy documentation
Adds the information concerning **exactly** what to return from sortBy -- it's not immediately clear from current documentation. Should save some trial and error when using this awesome feature.
> Docs: add additional sortBy documentation

- package.json
- rollup.config.js
- yarn.lock
update rollup config to replace 'process.env.NODE_ENV' occurrences for umd builds.
this would prevent the build from loading via the <script> tag since theres no process in browser
> chore: remove process reference in umd builds

- src/plugin-hooks/useSortBy.js
Fix sort subRows stop recursion when subRows length is one.
If row.subRows length is one, the subRows of row.subRows[0] will not sort in recursion
> Fix bug in sortData subRows

- src/plugin-hooks/useGroupBy.js
so that column order change done by grouping is applicable..on top of ordering done by useColumnOrder
> chore: Enforce `useColumnOrder` to be used before useGroupBy

- src/publicUtils.js
- src/utils.js
In order to be able to check if a column has a default renderer, we need them to be exposed constants instead of inline functions.
This way we could do, say:
```jsx
import { emptyRenderer } from 'react-table';
// …
if (column.Header === emptyRenderer) {
// …
}
```
Right now these are inline functions that cannot be compared with anything, so having publicly available references to these could help a lot when developing plugin-hooks that work with columns.
> fix: Use references to renderers instead of inline functions

- src/plugin-hooks/useSortBy.js
It would be nice and consistent if we have something like `setAllSortBy`, which sets sortBy state at once, similar to `setAllFilters`.
> feat(useSortBy): set sortBy state via method at once

- src/plugin-hooks/useRowSelect.js
Selection get broken when rows are expanded if the plugin order is wrong.
#2578
> Add useExpanded in the pluginOrder 

- docs/src/pages/docs/examples/material-ui-components.md
This Pr is fixing the links to the codesanbox.
> docs: fix material-ui codesanbox link

- docs/src/pages/docs/examples/material-ui-kitchen-sink.md
- examples/material-UI-kitchen-sink/README.md
Fixes #2658 
There were two main issues:
- docs/src/manifests/manifest.json had an entry for `/docs/examples/material-ui-kitchen-sink`, but the file name was `material-ui-enhanced-table`
- `material-ui` was actually `material-UI` in both the repository and in the codesandbox url
Page in production, prior to fix:
Page running locally, after fix:
I noticed all of the "Edit this page on GitHub" links were broken in the docs, so I left that link alone since it seems like a larger initiative to repair.
> docs: fix broken material ui kitchen sink links

- docs/src/pages/docs/examples/bootstrap-ui-components.md
- examples/bootstrap-UI-components/README.md
Bootstrap ui links are currently broken, this PR fixes them.
> docs: fix broken bootstrap ui links

- CHANGELOG.md
Just in case anyone is looking for where changelog entries are now.  Releases is pretty standard place already, but this saves a bit looking.
> docs: add link to Releases from CHANGELOG

- src/plugin-hooks/useGroupBy.js
Don't do costly operations (for calculation of groupedValues and leafValues), if the given column is not participating for aggregation, this will improve grouping performance many folds.
> fix(useGroupBy): Improve performance

- src/plugin-hooks/useResizeColumns.js
Since we upgraded React Table we started getting this error when we try to resize a column:
This fix should prevent the code from erroring.
> fix: do not crash when headerIdWidths is undefined

- docs/src/pages/docs/api/useSortBy.md
Spent two days at work trying to figure out how to do this! Turns out it existed on the table instance the whole time. Update the docs to reflect this.
> docs(useSortBy): add bullet point for setSortBy

- src/utils.js
When expandSubRows is set to false, subRows no longer get access to isExpanded or canExpand.
This change fixes this
> fix(utils): expose isExpanded and canExpand to subRows when expandSubRows is enabled

- src/pagination.js
When navigating to any page that is not the first one, and then sorting - the paginator input is not updated.
This means it will show the previous page number from the state, instead of getting the updated page number (which is 1) from the props.
> Fix pagination on sort

- .github/workflows/tests.yml
- package.json
This uses [bahmutov/npm-install](https://github.com/bahmutov/npm-install) to install NPM dependencies with caching without any configuration.
> chore(actions): add cache to NPM dependencies on GitHub actions

- src/plugin-hooks/useRowSelect.js
Change to toggleRowSelected reducer action to use the previous state. The reasoning for this change is that due to when row.isSelected was being updated when you would select another row it would deselect the previous row.
(#2171)
> fix(useRowSelect): change to toggleRowSelected reducer to use the previous state

- src/plugin-hooks/useFlexLayout.js
Table minimum width should be the sum of minimum width of all columns so the table can be responsive and shrink to the minimum width possible.
> fix(useFlexLayout): change table min width to be the sum of min width of all columns

- docs/src/pages/docs/api/useBlockLayout.md
The "See Column Options" link redirects to a 404 on the website. Provide two links, one for the website and one for GitHub.
> useBlockLayout.md - 404

- docs/src/pages/docs/api/useFlexLayout.md
Thanks for this great library - noticed this typo in link
> Fix link typo in docs 

- src/plugin-hooks/usePagination.js
Since the pageIndex is zero based it has to be less than pageCount
for canNavigate to be true. If pageIndex is equal to pageCount,
canNavigate should be false, otherwise a non-existing page would be accessed.
> fix: canNavigate check in goToPage reducer

- docs/src/pages/docs/api/useFilters.md
- docs/src/pages/docs/api/useGlobalFilter.md
This PR updates documentation for `useFilters` and `useGlobalFilter` to clarify what each does, removes old documentation (from v6, seemingly), improves wording and adds `state` details.
Currently, the documentation is hard to follow on why one would use `useFilters` compared to `useGlobalFilter`.  It was hard to know what each applied to (be it a row, column(s) or the table as a whole) without looking at the examples in action.  Once you see that, it makes sense - the former is filtering rows on a per-column basis and the latter is a single filter value being applied to _all_ columns at once.
These changes augment the existing docs with this info and explain the _other_ filter hook respectively, aiming to clarify what is being filtered and by what type of value.
Other improvements:
* …
> docs: rework filtering docs for clarity and completeness

- docs/src/pages/docs/api/useAbsoluteLayout.md
- docs/src/pages/docs/api/useBlockLayout.md
- docs/src/pages/docs/api/useExpanded.md
- docs/src/pages/docs/api/useFilters.md
- docs/src/pages/docs/api/usePagination.md
- docs/src/pages/docs/api/useResizeColumns.md
- docs/src/pages/docs/api/useRowSelect.md
- docs/src/pages/docs/api/useRowState.md
- docs/src/pages/docs/api/useSortBy.md
- docs/src/pages/docs/api/useTable.md
I noticed there were some broken links in the documentation due to an extra `.md`, when removing it the links work as expected.
> docs: fix broken links

- examples/expanding/package.json
- examples/expanding/yarn.lock
Previously this example was not running correctly, as it was using
react-table v7.0.0-rc15.
Fixes #2878.
> Update dependency versions in expand example

- docs/src/pages/docs/api/useSortBy.md
The internal implementation for the sort function returns 1 if rowA is larger and -1 if rowB is larger. So, I think the docs was supposed to be the other way around.
https://github.com/tannerlinsley/react-table/blob/6e2fe31ac028e543ce0f9d56168d5f922389fbbc/src/sortTypes.js#L75-L77
> docs(useSortBy): fix sort type function return values

- docs/src/pages/docs/api/useSortBy.md
- src/plugin-hooks/tests/useSortBy.test.js
- src/sortTypes.js
Add two new build in sort types. Current sort types are unchanged.
Suggested in https://github.com/tannerlinsley/react-table/issues/3093
1.  `number`
Sorts only numerical values inside column.
2.  `string`
Does what is suggersted in https://github.com/tannerlinsley/react-table/issues/3137.
Sorts case-insensitively until there is a tie and then sorts case-sensitive.
> Add two new built in sort types 

- docs/src/pages/docs/api/useTable.md
- docs/src/pages/docs/faq.md
- docs/src/pages/index.js
Change `it's` to `its` (3 occurrences).
> docs: fix typo

- packages/table-core/src/features/Sorting.ts
Changed instance.resetSorting to accept an optional columnId and only remove sorting from that 1 column. 
Added column.resetSorting()
> #3785 add column.resetSorting()

- packages/table-core/src/createTable.tsx
I think 5636cf45298d164520042e4a9a5b848419f5f376 broke inference of the value type based on the accessor. The values are stuck at the default `unknown`.
```tsx
const table = createTable<Disk>()
const columns = table.createColumns([
table.createDataColumn('name', {
header: 'Name',
cell: ({ value }) => <div>{value}</div>, // <-- value has type unknown
}),
table.createDataColumn((d) => d.state.state, {
id: 'status',
header: 'Status',
cell: ({ value }) => <DiskStatusBadge status={value} />, // also unknown
}),
])
```
I tested this fix in my project by modifying the copy inside `node_modules` and it did bring back the inference, so it seems to be the right idea even though it's ugly. All I really did was bring back what was going on before the breaking commit: …
> Use accessor type to narrow value type in createDataColumn

- packages/table-core/src/features/Expanding.ts
A small and efficient addition to the expanded feature I use in my project.
In most cases where expanded state is not handled manually, this should be an instant constant lookup time.
> add getIsSomeRowsExpanded instance property (v8 alpha)

- packages/table-core/src/features/Expanding.ts
- packages/table-core/src/features/Pinning.ts
Another small utility function to tell whether or not the current table state has column pinning on at all.
This can be useful if in a split table needs to add specific styles and logic based on whether or not pinning is splitting the table.
[Example here](https://github.com/KevinVandy/material-react-table/blob/0d0fc6a0800e99a52e6c27adee5a6091413bf80b/src/table/MRT_TableContainer.tsx#L80)
> Feat getIsSomeColumnPinned table instance method (v8)

- src/plugin-hooks/tests/useResizeColumns.test.js
- src/plugin-hooks/useResizeColumns.js
👋 hey internet, here's an optimization that significantly improves column resize performance
- i'm consistently seeing a 30-50% reduction in the number of calls to `dispatch()` when i interactively drag the handle back and forth in the "column-resizing" demo
- want to debug this even farther locally or on codesandbox?
- this commit demonstrates how to add some console statements to show the number of calls: 37a69f5
- you can pull this branch and revert that commit to measure this interactively yourself if you want to
- partially addresses #3165
> perf(useResizeColumns): optimize dispatch count

- src/plugin-hooks/useRowSelect.js
This will fix the errors referenced by #2833 and #3071. This will also fix a "TypeError: Cannot read property 'subRows' of undefined" error. These errors appear when a row does not exist, whether removed from the data or filtered out, but there is still a reference in the selected state.
> fix: check for row existence in handleRowById

- packages/table-core/src/core.tsx
- packages/table-core/src/createTable.tsx
In my use of react-table v8, there are dozens of instances where different render logic and css are wanted based solely on whether or not a column is a display column, data column, or whether or not a column has child columns.
I believe simply recording with of `table.createDataColumn(...)`, `table.createDisplayColumn(...)`, or `table.createDataColumn(...)` was used to create the column could be very useful in simplifying this kind of logic.
> feat: Record columnDefType to CoreColumn (v8)

- packages/table-core/src/utils.tsx
Vercel builds throw an error `ReferenceError: performance is not defined` because Vercel supports a max node version of node v14 still, where the performance module is not yet globally defined.
Stack Overflow: https://stackoverflow.com/questions/46436943/referenceerror-performance-is-not-defined-when-using-performance-now
> import performance module for node < v16 until platforms like Vercel support node 16

- packages/table-core/src/utils.tsx
Reverts TanStack/react-table#3833
> Revert "import performance module for node < v16 until platforms like Vercel support node 16"

- examples/basic/yarn.lock
- examples/column-ordering/yarn.lock
- examples/column-pinning/yarn.lock
- examples/column-sizing/yarn.lock
- examples/column-visibility/yarn.lock
- examples/expanding/yarn.lock
- examples/filters/yarn.lock
- examples/fully-controlled/yarn.lock
- examples/grouping/yarn.lock
- examples/pagination/yarn.lock
- examples/row-selection/yarn.lock
- examples/sorting/yarn.lock
- packages/react-table-devtools/package.json
- scripts/publish.ts
As part of digging into the examples and thinking about how to upgrade a complex project from v7 to v8 I identified some opportunities for cleanup:
- tidy up lockfiles and keep them in sync with the latest release
- clean up unused code in some examples
This PR addresses the first one, and I've added it to the `scripts/publish.ts` script and tested locally:
```
$ TAG=v8.0.0-alpha.28 ./node_modules/.bin/ts-node scripts/publish.ts
Tag is set to v8.0.0-alpha.28. This will force release all packages. Publishing...
Parsing 1397 commits since v8.0.0-alpha.28...
Generating changelog...
Version 8.0.0-alpha.28 - 2022-04-17, 2:20 p.m.
Manual Release: v8.0.0-alpha.28
- @tanstack/table-core@8.0.0-alpha.28
- @tanstack/react-table@8.0.0-alpha.28
- @tanstack/react-table-devtools@8.0.0-alpha.28
Building …
```
> keep example lockfiles in sync when releasing

- packages/table-core/src/features/Pagination.ts
This update will ensure that the `getCanNextPage` function works correctly when doing server side pagination (or some other form of pagination handled outside of react-tables internals).
One thing to not is while I've manually tested this, my changes didn't trigger / get picked up by any of the tests when running `yarn dev`. I could add one but that could take up some time to figure out, is there an outline on how to quickly add a test for v8? I see some of the current tests are still from the old (v7).
> fix(getCanNextPage): Use the `getPageCount` function over manual calculation on the fly

- src/plugin-hooks/useExpanded.js
#3061 mentions below.
> When using React.StricttMode you are unable to collapse all rows using the "expand/collapse all" button after expanding them. This can be seen in the React Table "Expanding" official example just by running the app in strict mode.
> https://codesandbox.io/s/exciting-bartik-hrbeu?file=/src/index.js
I change `isAllRowsExpanded` from `instance` to recalculating it by using `state` because `isAllRowsExpanded` from `instance` is toggled twice on React.StrictMode. Once `isAllRowsExpanded` from `instance` gets `true`, it toggles twice and always returns `true` whenever the "Toggle All Rows Expanded" button is clicked.  
**Test result**
```bash
PASS   unit  src/plugin-hooks/tests/useExpanded.test.js
✓ renders an expandable table (91ms)
Test Suites: 1 passed, 1 total
Tests: …
```
> fix(useExpanded): state of isAllRowsExpanded on React.StrictMode

- packages/solid-table/src/index.tsx
This PR fixes the transpilation issue with solid's jsx by removing jsx syntax with `createComponent` call.
> fix solidjs jsx issue

- docs/src/pages/docs/api/overview.md
- docs/src/pages/docs/api/useGridLayout.md
- src/plugin-hooks/tests/useGridLayout.test.js
- src/plugin-hooks/useGridLayout.js
Resolves #3537 
`useGridLayout` could not display header groups by default. This seemed like a bug as it is fairly common functionality that it should be able to handle.
Header groups can be supported with the grid layout by using the css grid-column property with a span of the column's `totalVisibleHeaderCount`.
`useGridLayout` has a bug that comes from 'auto' or 'fr' units. When some resizing columns, the cursor doesn't stay with the resizer handle because 'auto' width columns rescale based on the column being resized. e.g. columnResizing state thinks the column width is 150, but it is actually 200 because of grid 'auto' resizing.
This column resizing bug was fixed by locking the width of all columns not being resized. Now, while resizing, this behaves exactly like the Resizing example …
> fix(useGridLayout): Support header groups

- packages/table-core/src/features/Filters.ts
remove unused plural type `enableGlobalFilters` 
`enableGlobalFilter` (singular) remains
> remove unused enableGlobalFilters filter type

- docs/src/pages/docs/api/useSortBy.md
According to `sortTypes.js` these are the new sortTypes.
Thanks all for your great work on this project.
> Update useSortBy docs

- packages/vue-table/tsconfig.json
- tsconfig.base.json
- tsconfig.json
- yarn.lock
The `vue-table` and `solid-table` packages weren't outputting type declarations because they weren't referenced in the root `tsconfig.json`. This PR fixes that.
> fix type declarations for adapters

- packages/table-core/src/createTable.ts
I can't figure out how to run a global typechecker so I can't confirm the types pass. But hopefully CI will do that.
> Take out `extends object` on row, table meta, and column meta

- packages/react-table/src/index.tsx
The react adapter was calling `useLayoutEffect` which showed a warning during SSR. This PR makes the `useLayoutEffect` isomorphic and switches it for `useEffect` on server
> fix ssr warning due to `useLayoutEffect`

- docs/api/column-pinning.md
- docs/api/row-selection.md
Left some TODOs for some row model methods that I believe Tanner would be able to explain and document much better than I could, but otherwise, filled out ~90% of initial row-selection docs
> row-selection initial docs

- babel.config.js
This PR updates the babel targets so as to not transpile the classes in svelte adapter to functions, which caused runtime issues. The target it now sets is `defaults, not ie 11, not ie_mob 11`, which might be too high, but I think that most users of react-table are probably already transpiling their code to lower targets if they want browser compat, so it shouldn't be an issue
> fix: update the babel targets to not transpile classes

- packages/svelte-table/src/index.ts
This PR fixes the issue with svelte adapter's render method where passing a function would make it think that it is a svelte component. It adds additional checks to check the input type and wraps it in a component accordingly
> fix svelte adapter's render method

- packages/vue-table/src/index.ts
The PR fixes the type of `render` function in vue adapter. The previous type didn't allow the cells/columns to be a string and required for it to be a vnode. This allows it to be a number, string or boolean and aligns it with the react adapter
> fix vue render type

- packages/table-core/src/features/Filters.ts
I realize that there is no check for filtering the boolean values in the filter feature.
In my opinion below code snippet in `getAutoFilterFn` in `/Filters.ts` may satisfy the issue.
```typescript
if (typeof value === 'boolean') {
return filterFns.equals
}
```
> add a check for filtering the data columns with type boolean

- docs/guide/04-column-defs.md
> docs: fix jsx tag in column definitions docs

- docs/guide/column-sizing.md
Based on the current source
https://github.com/TanStack/table/blob/33169d3c2459215c5601b3ea062103c5ffda1548/packages/table-core/src/features/ColumnSizing.ts#L80-L84
This snippet is stale and mentions `width`s, which are not part of the v8 API
> update code snippet to reflect `size` is used for these fields

- docs/guide/01-overview.md
This will fix some typos I found when I was browsing the docs.
> Fix typos in overview docs

- package.json
- yarn.lock
Per #3962:
* Update @babel/core and @babel/plugin-transform-regenerator to 7.18.0, so that the generated code doesn't rely on the regeneratorRuntime global anymore.
Babel config already uses `babel-transform-runtime`.
> Update babel (fix for #3962)

- packages/table-core/src/aggregationFns.ts
The sum aggregate function always returned zero for me. It seems like a `.getValue()` is missing there.
> Fix sum aggregate function

- docs/src/pages/docs/api/useGroupBy.md
Other plugin pages explicitly mention this flag (e.g. useExpanded), but useGroupBy didn't — added it in!
FYI: I didn't test locally, just made the change in the Github editor. Hopefully, it looks right 🤞
> Update useGroupBy docs to mention `autoResetGroupBy`

- packages/react-table/src/index.tsx
```ts
type React.ComponentType<P = {}> = React.ComponentClass<P, any> | React.FunctionComponent<P>
```
Type `React.Component` is used for component instance and it is not callable.
The tests and build will pass after merging pr [#4086](https://github.com/TanStack/table/pull/4086).
> fix(react-table): type `Renderable`

- packages/table-core/src/features/RowSelection.ts
This is an attempt to fix #4121. It adds a check into the row `canSelect` method before marking it as selected.
> fix: add a check to assert row can be selected before selection

- packages/table-core/src/features/Expanding.ts
Discussion here -
https://github.com/TanStack/table/discussions/4137
Details:
GetRowCanExpand should override other condition checks when getCanExpand is called.
> fix: getRowCanExpand override other conditions for getCanExpand

- packages/table-core/src/features/RowSelection.ts
This is another fix for an issue which arose in #4128. As discussed in the issue, https://github.com/TanStack/table/issues/4121#issuecomment-1180721652, the `getIsAllRowsSelected` method doesn't use a filter to only match the rows which are allowed to be selected. This PR adds this behavior into it.
> Fix bug in `getToggleAllRowsSelectedHandler` when there are non-selectable rows.

- src/hooks/useTable.js
React 18 removed some logic from `useReducer()` where a dispatch would eagerly call reducers to recompute the state so now reducers will be called after render. This poses a problem for `useTable()` because during render it mutates the `instance` by spreading in `props` and does not expect this to happen before reducer execution. We were passing a `pageCount: undefined` prop to `useTable()` and by the time the reducer executes `instance.pageCount` is been overwritten, causing a bug in our app. In the Codesandbox reproduction you can see that hitting the "next" button will not work. I understand that our abstraction around `useTable()` probably shouldn't be passing this prop when `undefined` but the behavior change was unexpected and I wonder if it breaks any other assumptions that this …
> fix(useTable): work around React 18 useReducer eager bailout change

- packages/table-core/src/features/RowSelection.ts
This is a small fix for a recently introduced bug described in this issue https://github.com/TanStack/table/issues/4212 where `getIsSomeRowsSelected` returned `true` even when no rows were selected.
> Fix a bug in `isSomeRowsSelected`

- packages/table-core/src/types.ts
Some examples show that when you have an `accessorKey` you don't need a `header` or `id`. This should make `header` and `id` optional when an `accessorKey` is present. 
Other option is to just update the examples column defs that are wrong.
> fix: columns with accessor key should have optional id and header

- .github/ISSUE_TEMPLATE/config.yml
- README.md
- old-examples/expanding/README.md
- old-examples/grouping-column/README.md
- old-examples/pagination/README.md
- old-examples/pivoting/README.md
- old-examples/rmwc-components/README.md
- old-examples/sub-components-lazy/README.md
Updates links to point to `TanStack/table` instead of `tannerlinsley/react-table`.
> Update repo links to TanStack/table

- docs/guide/column-ordering.md
- docs/guide/column-pinning.md
- docs/guide/grouping.md
> fix(docs) links between column sorting pages #4394

- packages/match-sorter-utils/__tests__/match-sorter-utils.test.ts
- packages/match-sorter-utils/src/index.ts
- rankItem was not using the accessor specific threshold and neither the general threshold
- rankItem did not set `passed` to true when using accessors
- some basic regression tests
> rankItem in match-sorter-utils use threshold when using accessors

- packages/table-core/src/features/ColumnSizing.ts
add missing event listeners for `touchmove` and `touchend`
fixes #4321
> fix columnn resize not working on touch devices

- packages/table-core/src/core/column.ts
Provide a more helpful error message when using nested keys with missing data.
Fixes: https://github.com/TanStack/table/issues/4320
> feat: error message for invalid nested keys

- docs/guide/column-defs.md
When using an `accessor` type column helper in a top level column defs array where the array is also typed, you get the type error brought up #4382. It was also mentioned that the solution here is to not type the array, so this PR removes the typing from the example in the docs.
> docs: Remove extra typing for Column Defs

- packages/table-core/src/columnHelper.ts
- packages/table-core/src/core/cell.ts
- packages/table-core/src/core/column.ts
- packages/table-core/src/core/headers.ts
- packages/table-core/src/core/row.ts
- packages/table-core/src/core/table.ts
- packages/table-core/src/features/ColumnSizing.ts
- packages/table-core/src/features/Expanding.ts
- packages/table-core/src/features/Filters.ts
- packages/table-core/src/features/Grouping.ts
- packages/table-core/src/features/Ordering.ts
- packages/table-core/src/features/Pagination.ts
- packages/table-core/src/features/Pinning.ts
- packages/table-core/src/features/RowSelection.ts
- packages/table-core/src/features/Sorting.ts
- packages/table-core/src/features/Visibility.ts
- packages/table-core/src/types.ts
- packages/table-core/src/utils.ts
This PR optimises TypeScript types, following [Microsoft's Writing Easy-to-Compile Code](https://github.com/microsoft/TypeScript/wiki/Performance#writing-easy-to-compile-code) section of the TypeScript wiki.
After migrating to version 8, I encountered severe performance degradation in a file with 100+ column definitions, to the point that TS type checking and autocomplete ceased to function in the editor. I believe IntelliJ uses the standard TypeScript language server, so these issues may also crop up in other editors.
The changes in this PR have resolved the issues I was having. Most of the work in this PR migrates from `type` to `interface` based type definitions, but there are a few smaller optimisations as well. The aforementioned link to the TS wiki details the benefits of using …
> perf: optimise types

- packages/react-table/__tests__/makeTestData.ts
- packages/table-core/__tests__/getGroupedRowModel.test.ts
- packages/table-core/__tests__/makeTestData.ts
- packages/table-core/src/utils/getGroupedRowModel.ts
I maintain an application which renders a virtualized `react-table` table with up to 50k rows, 50 columns and up to 3 grouped columns. We were noticing huge performance problems with grouping and tracked it down to `[...previous, row]` in `groupBy` inside of `getGroupedRowModel`. This PR fixes that issue and adds a spec to verify the performance of that scenario.
* When grouping data that has large clusters of values, generating grouped columns becomes extremely slow. For instance: 50k rows, 3 grouped columns, each grouped column has an identical value (so each groups together 50k rows each) - takes ~30 seconds
* The performance bottleneck is `[...previous, row]` - it has to recreate the previous array over and over again, getting slower and slower each iteration. Using `.push` instead …
> [v8] Improve grouping performance on large clusters of values

- packages/table-core/__tests__/getGroupedRowModel.test.ts
The previous [github actions pipeline](https://github.com/TanStack/table/actions/runs/3451872738/jobs/5761396109#step:4:319) failed by a margin of 13ms. The unit test should add some margin for when resources are not as strong in the Github pipelines. Increasing margin by 50%.
> make unit test time limit more lenient

- packages/table-core/src/filterFns.ts
`includesString` and `includesStringSensitive` doesn't filter falsey values.
> fix: IncludesString and IncludesStringSensitive includes `undefined` values

- .github/workflows/pr.yml
- packages/react-table/__tests__/features/RowSelection.test.tsx
This adds a test for the behaviour described in #4121. It also covers the bug which was fixed in #4212. It also adds a few more common use cases.
> tests: add tests for row selection feature

- packages/table-core/src/types.ts
**This PR includes:**
Sets the correct type for `AccessorKeyColumnDef#accessorKey`. Currently with out this PR it doesn't give the correct auto complete, with this fix it does.
> fix(types): correctly set type for `AccessorKeyColumnDef#accessorKey`

- docs/api/core/column-def.md
It took me a minute to realise why extending `meta` didn't work. Just thought it might be worth making the example work out of the box.
> Update ColumnDef docs to make extending meta clearer

- docs/api/features/sorting.md
I spend quite some time looking for a way to change default behaviour when changing sort order with `getToggleSortingHandler` repeatedly. I've seen this option in docs, but I didn't understand what it does at first, I think this should be clarified a bit more.
Also `true` feels like default behaviour - should that be explicitly said as well?
This is proposed change, but I'm very much open for the wording changes to make it more understandable/clear.
> docs(sorting): Clarify enableSortingRemoval effect

- docs/api/core/table.md
The type for defaultColumn in the documentation is incorrect since it shows an array type.
> Small documentation fix for defaultColumn type

- docs/api/features/filters.md
- packages/table-core/src/features/Filters.ts
- packages/table-core/src/utils/filterRowsUtils.ts
Proposal: new `maxLeafRowFilterDepth` filter option
Problem: Sometimes in grouped or expanded sub-row tables, a user wants to search/filter for a parent row and view all of its child rows. Currently most of those child rows get filtered out, even if using the `filterFromLeafRows` option.
Solution: `maxLeafRowFilterDepth` allows how many levels deep in the row tree that filtering should be applied. A value of `0` here will only apply filters to the root level rows, and so on. Defaults to `100` if not specified to keep current functionality.
maxLeafRowFilterDepth was the 3rd name I settled on for this feature. I originally had it as a boolean called `filterLeafRows`. Could consider a better name.
> feat: new maxLeafRowFilterDepth filter option

- babel.config.js
- package.json
- packages/match-sorter-utils/package.json
- packages/match-sorter-utils/tsconfig.json
- packages/react-table-devtools/package.json
- packages/react-table-devtools/tsconfig.json
- packages/react-table/package.json
- packages/react-table/tsconfig.json
- packages/solid-table/package.json
- packages/solid-table/tsconfig.json
- packages/svelte-table/package.json
- packages/svelte-table/tsconfig.json
- packages/table-core/package.json
- packages/table-core/src/features/Filters.ts
- packages/table-core/tsconfig.json
- packages/vue-table/package.json
- packages/vue-table/tsconfig.json
- rollup.config.ts
- tsconfig.base.json
- yarn.lock
This PR should bring better ESM support for both older and newer bundlers.
I tried to replicate the setup that we have in https://github.com/TanStack/query.
There are few typescript issues in `packages/table-core/src/features/Filters.ts`
It would be ideal if people using different adapters could test this before integrationg to main branch.
> feat: better esm support

- scripts/publish.ts
@KevinVandy Small fix to stop requiring `browser` field in `package.json` during deploy as it's breaking older webpack versions.
> fix: do not check for `browser` in package.json

- docs/api/core/column-def.md
I didn't find any documentations on how we access column meta data. Luckily found this solution in this issue: https://github.com/TanStack/table/issues/3983#issuecomment-1142334750. I think it's better to add it to current documentations.
> docs(column): add explanation on how to access meta

- .github/workflows/pr.yml
I thought it would be easier to see which step failed in the future if they are in a separate step.
> Define separate steps in pr.yml

- packages/table-core/src/features/ColumnSizing.ts
When onColumnSizingChange is used without react.strictmode / production the function does not return the correct updated values. This breaks the resize feature as discussed in https://github.com/TanStack/table/issues/4479
> Fix: onColumnSizingChange does not return correct value when react.strictmode is not used

- babel.config.js
I've tested this locally installing dependencies using `npm install` the same way as the CI scripts do.
See https://github.com/TanStack/table/issues/4500#issuecomment-1374953210 for context.
> #4500 - Force babel to transform optional chaining

- packages/solid-table/package.json
As it stands, one ends up with hydration errors in certain SSR situations.
This PR adds `solid` to the package.json exports map, along the lines of what [@solidjs/router](https://github.com/solidjs/solid-router/blob/main/package.json#L23) and [@tanstack/solid-query](https://github.com/TanStack/query/blob/main/packages/solid-query/package.json#L19) do. In my local testing, this fixes the hydration error.
> fix(solid-table): add solid to package.json exports table to fix hydration errors

- docs/api/core/table.md
- packages/table-core/src/core/column.ts
- packages/table-core/src/core/row.ts
- packages/table-core/src/core/table.ts
- packages/table-core/src/features/ColumnSizing.ts
- packages/table-core/src/utils/getFacetedMinMaxValues.ts
- packages/table-core/src/utils/getFacetedUniqueValues.ts
- packages/table-core/src/utils/getFilteredRowModel.ts
- packages/table-core/src/utils/getGroupedRowModel.ts
- packages/table-core/src/utils/getSortedRowModel.ts
add safe check for nested accessor keys with dot notation to make sure data is not undefined, warn if not, but do not crash.
allow table.getColumn to return undefined if no column is found. Console error still, but do not crash
> fix: allow for null nested data and do not crash when invalid column id is passed

- docs/guide/overview.md
changed 'provide' to 'provides'
> Fix typo in Overview guide

- .github/workflows/pr.yml
- nx.json
- package.json
- project.json
- yarn.lock
<div align="left">
<a href="https://www.youtube.com/watch?v=ewA42CaCF8s" target="blank">
</a>
</div>
+ Mainly a like-for-like for the following package scripts: `build`, `test:ci`, `typecheck`
+ These three commands will still be called as they have been (e.g.: `npm run build`) and have the same effect. They have been optimized to add intelligent caching so we never need to run the same command on the same code twice!
+ (`build` was also optimized to run it's `rollup` and `tsc` commands in parallel, whereas before they were in sequence)
+ The `pr` workflow file was updated - it will still run the same checks as it had before, but it will now run all checks in parallel (as opposed to in sequence)
+ Adding `nx` means that we can use nx for task running which gives us some nice things - for …
> Introducing nx for caching

- .github/workflows/pr.yml
+ adds caching of the node_modules between github action runs
+ changes to: `yarn install --frozen-lockfile` as the install step in ci (to match our yarn.lock file in source)
Control run: https://github.com/TanStack/table/actions/runs/4458215445
New run w/ node_module caching: https://github.com/TanStack/table/actions/runs/4465120375
<table>
<tr>
<th></th>
<th>Control run</th>
<th>New run w/ node_module caching</th>
</tr>
<tr>
<th>"Install Node.js" Step</th>
<td>0s</td>
<td>18s</td>
</tr>
<tr>
<th>"Install Dependencies" Step</th>
<td>1m 4s</td>
<td>23s</td>
</tr>
<tr>
<th>Total Time</th>
<td>3m 52s</td>
<td>2m 58s</td>
</tr>
</table>
> adding caching for package deps in workflows

- packages/react-table/__tests__/features/RowSelection.test.tsx
- packages/table-core/src/features/RowSelection.ts
Resolves #4757 
The fix for #4690 didn't consider the case where there weren't any selectable rows. `paginationFlatRows` needed to be filtered down to the selectable rows before using it to verify that there weren't any unchecked rows within that collection. The same applies to determining the indeterminate state in `getIsSomePageRowsSelected`.
> fixes selection logic for getIsAllPageRowsSelected & getIsSomePageRowsSelected

- packages/svelte-table/src/index.ts
Currently the flexRender function checks if the result of `cell` function is a Svelte component, and if it is, it just returns the actual Component instead of rendering the component with the props. This PR fixes this issue
> Render the actual component for svelte when returned from cell function

- docs/guide/column-defs.md
fixes #4717 
before:
`There are 2 ways to do this:`
after
`There are 3 ways to do this:`
> fixes Minor typo in docs for column accessors

- docs/api/features/filters.md
The [default implementation](https://github.com/TanStack/table/blob/423d46ecce8d1f3f02c78e5d833b54112c21136c/packages/table-core/src/features/Filters.ts#L196) for `getColumnCanGlobalFilter` will return `false` if the value in the first row is not a `string` or `number`. This PR attempts to clarify this.
This is related to #4711
> fix(docs): clarify default implementation

- docs/api/features/column-ordering.md
- docs/api/features/column-pinning.md
- docs/api/features/column-sizing.md
- docs/api/features/column-visibility.md
- docs/api/features/expanding.md
- docs/api/features/filters.md
- docs/api/features/grouping.md
- docs/api/features/pagination.md
- docs/api/features/sorting.md
Fix wording by replacing `Table API API` with `Table API`
> docs: Fix wording by replacing 'Table API API' with 'Table API'

- examples/svelte/basic/src/App.svelte
Made this change to fix the following error: 
```
manifest.js?t=1680685613141:48 SyntaxError: The requested module '/node_modules/.vite/deps/@tanstack_svelte-table.js?v=8133f374' does not provide an export named 'ColumnDef'
```
> Fixed types import error.

- packages/svelte-table/src/index.ts
This handles the case when a column is defined like:
```
{
id: 'columnId',
header: 'Header',
accessorKey: 'property',
},
```
but item[accessorKey] is null or undefined.
> fix: handle null/undef values when flexRendering function-type component in svelte-table

- docs/api/features/grouping.md
- examples/react/grouping/src/main.tsx
- packages/table-core/src/features/Grouping.ts
- packages/table-core/src/utils/getGroupedRowModel.ts
Adds an option to column definitions to allow the user to specify a custom value to be used for row grouping.
> Feat get grouping value

- docs/api/features/filters.md
- docs/api/features/grouping.md
- docs/api/features/sorting.md
This pull request replaces the `useTable` method as it has been removed in version 8. The React adapter method has been used as an example.
> docs: Fix table method

- examples/react/row-selection/src/main.tsx
Changed `table.getSelectedFlatRows()` to `table.getSelectedRowModel().flatRows` which is what the button does.
> docs: Fixed button name to better represent its function

- docs/config.json
- examples/vue/pagination-controlled/src/App.vue
- examples/vue/pagination-controlled/src/useService.ts
- examples/vue/pagination-controlled/tsconfig.dev.json
- tsconfig.json
This PR fixes a typechecking error related to this example. I've also enabled the example in `tsconfig.json` and added it to `docs/config.json`. Finally, I ran everything through prettier.
See #4956 for more details.
> fix: vue controlled pagination example

- packages/svelte-table/package.json
Svelte 4 was announced back in June 2023
https://svelte.dev/blog/svelte-4
But Tanstack table doesn't allow version 4.x.x which is preventing all of us Svelte table users to use Svelte 4 which has been out for a month now. Svelte 4 doesn't have any breaking changes (very minor ones related to custom elements), so I don't expect anything to break for Tanstack, and it should unblock people from using Svelte 4.
There is no bug for this, but there is a discussion thread
https://github.com/TanStack/table/discussions/4944
> Add support for Svelte 4

- packages/table-core/src/utils/filterRowsUtils.ts
I believe there is an obvious typo in the `filterRowsUtils.ts::filterRowModelFromLeafs`, causing the filteredRowModel.flatRows to always be empty, and also `column.uniqueFacetedValues()` to be an empty array (which is what tipped me off). There was no execution path, where the `newFilteredRowsById` array gets populated. 
fixes: #4768
> fix filtering bug when filterFromLeafRows = true

- docs/api/features/sorting.md
Fix typos and change the sortUndefined default value from `false` to `1` in docs, to reflect the default in the code.
https://github.com/TanStack/table/blob/9ef186f53dbad3047e8cc968a665794de7c44314/packages/table-core/src/features/Sorting.ts#L116-L121
> docs: Update sorting.md

- packages/table-core/__tests__/RowSelection.test.ts
- packages/table-core/src/features/RowSelection.ts
Full description on the linked issue (#5060)
* `getIsSomeRowsSelected()` and `isSubRowSelected()` now ignore rows that cannot be selected.
* `toggleSelected()` now doesn't skip propagating toggle on rows that cannot be selected.
> Row selection should ignore unselectable rows (fix #5060)

- docs/api/core/cell.md
- docs/api/core/header.md
- docs/api/core/row.md
- docs/api/features/column-visibility.md
- docs/api/features/expanding.md
- docs/api/features/filters.md
- docs/api/features/grouping.md
- docs/api/features/pinning.md
- docs/api/features/row-selection.md
- docs/api/features/sorting.md
- packages/react-table/src/index.tsx
- packages/table-core/src/columnHelper.ts
- packages/table-core/src/core/cell.ts
- packages/table-core/src/core/column.ts
- packages/table-core/src/core/headers.ts
- packages/table-core/src/core/row.ts
- packages/table-core/src/core/table.ts
- packages/table-core/src/features/ColumnSizing.ts
- packages/table-core/src/features/Expanding.ts
- packages/table-core/src/features/Filters.ts
- packages/table-core/src/features/Grouping.ts
- packages/table-core/src/features/Ordering.ts
- packages/table-core/src/features/Pagination.ts
- packages/table-core/src/features/Pinning.ts
- packages/table-core/src/features/RowSelection.ts
- packages/table-core/src/features/Sorting.ts
- packages/table-core/src/features/Visibility.ts
- packages/table-core/src/filterFns.ts
- packages/table-core/src/types.ts
- packages/table-core/src/utils.ts
This PR adds jsdoc descriptions and links to the api reference and guide docs to every option and api in TanStack Table
About a dozen options and apis that were missing from the docs have also been added
> add jsdoc comments

- packages/table-core/src/utils/getSortedRowModel.ts
Full description on the linked issue #5103
* Sorting subrows unintentionally updates CoreRowModel subrows. Do a deeper copy when beginning to sort instead.
> Fix subrow reset sorting (fix #5103)

- packages/table-core/src/core/row.ts
Currently, with certain filtering or pagination features applied, `row.getParentRow()` and `row.getParentRows()` has the possibility to throw an error when trying to find rows that exist, just not in the filtered row model.
Passing in `true` as the second argument to `table.getRow()` should fix this.
> fix: getParentRow should search all row model rows

- packages/table-core/__tests__/Sorting.test.ts
- packages/table-core/src/sortingFns.ts
Full description on the linked issue #5108
> Better alphanumeric sort of bools and floats (fix #5108)

- packages/table-core/src/features/RowSelection.ts
Fixed the description of `getIsSomePageRowsSelected` and `getIsSomeRowsSelected` to match https://tanstack.com/table/v8/docs/api/features/row-selection.
> Update jsdoc comments

- docs/guide/column-defs.md
I had some columns whose accessorKeys were nested keys, like `foo.bar`.
I had to go [digging through the code](https://github.com/TanStack/table/blob/a1e9732e6fc3446a2ae80db72a1f2b46a5c11e46/packages/table-core/src/core/column.ts#L82) to figure out why the column id for those columns weren't `foo.bar`, and what they were instead.
Adding this comment to hopefully clarify this for other people! Let me know if there's anything I should change/update.
> Clarify column id documentation for nested keys

- docs/api/features/row-selection.md
* Added note about row selection being index based by default
* Added a link for how row selection can be managed with a custom id using the `getRowId` option on the core table api.
* Referenced the use case of manual pagination as it is one of the most likely scenarios that using a custom id is necessary for row selection.
This should help developers understand how row selection is implemented and how it relates to other features within the table.
> Improve row selection docs

- docs/api/features/column-sizing.md
- packages/table-core/src/features/ColumnSizing.ts
This PR adds support for RTL column resizing by adding a `columnResizeDirection` to column resize options, as discussed in #4331
> Feature: Add columnResizeDirection to support RTL column resizing

- packages/table-core/src/types.ts
Hello, this is a short pull request to add some missing "export" clauses to some types.
Using a nx monorepo, one of my buildable modules fails to build with the following errors:
```
TS4023: Exported variable 'myHook' has or is using name 'AccessorKeyColumnDefBase' from external module ".../node_modules/@tanstack/table-core/build/lib/types" but cannot be named. 
TS4023: Exported variable 'myHook' has or is using name 'IdIdentifier' from external module ".../node_modules/@tanstack/table-core/build/lib/types" but cannot be named.
TS4023: Exported variable 'myHook' has or is using name 'StringHeaderIdentifier' from external module ".../node_modules/@tanstack/table-core/build/lib/types" but cannot be named.
```
I have yarn linked react-table and table-core, and it resolved my build issues. …
> fix(types): export types IdIdentifier, StringHeaderIdentifier, AccessorKeyColumnDefBase

- examples/solid/basic/package.json
- examples/solid/bootstrap/package.json
- examples/solid/column-groups/package.json
- examples/solid/column-ordering/package.json
- examples/solid/column-visibility/package.json
- examples/solid/sorting/package.json
- examples/svelte/basic/package.json
- examples/svelte/column-groups/package.json
- examples/svelte/column-ordering/package.json
- examples/svelte/column-pinning/package.json
- examples/svelte/column-visibility/package.json
- examples/svelte/sorting/package.json
- examples/vue/basic/package.json
- examples/vue/column-ordering/package.json
- examples/vue/column-pinning/package.json
- examples/vue/pagination-controlled/package.json
- examples/vue/pagination/package.json
- examples/vue/row-selection/package.json
- examples/vue/sorting/package.json
- package.json
- yarn.lock
An incremental step to bringing the workspace config more in line with TanStack Query. TS version is pinned so it doesn't auto update (TS doesn't use semantic versioning).
> chore: Migrate from TypeScript 4.9 to 5.2

- .github/workflows/ci.yml
- nx.json
- Uses `"namedInputs"` config from query repo.
- Set CI to only run on main repo.
> chore: Update Nx caching inputs

- packages/table-core/src/core/table.ts
> fix: getRow with expanded row model and selection

- docs/config.json
- examples/solid/filters/.gitignore
- examples/solid/filters/README.md
- examples/solid/filters/index.html
- examples/solid/filters/package.json
- examples/solid/filters/src/App.tsx
- examples/solid/filters/src/ColumnFilter.tsx
- examples/solid/filters/src/index.css
- examples/solid/filters/src/index.tsx
- examples/solid/filters/src/makeData.ts
- examples/solid/filters/tsconfig.dev.json
- examples/solid/filters/vite.config.ts
Added a working example in Solid.JS for both global and column filters. Format and structure follows the React example reasonably closely - however I did omit a few things (eg. sorting, pagination) as I felt they were separate Table features and I did not want to complicate the code for this example.
> docs: add solid filters example

- docs/api/core/column-def.md
Using `@tanstack/table-core` doesn't work with `@tanstack/react-table`.  
I found this fix here: https://github.com/TanStack/table/discussions/4157#discussioncomment-3224614
I'm open to feedback, but I would like to fix the docs so it easy to copy the example into projects.
> docs: fix meta data example

- package.json
- pnpm-lock.yaml
- scripts/publish.js
- scripts/tsconfig.json
- tsconfig.json
There is an async/await error in `scripts/publish.js` which manifested in the TanStack Form repo. This change ensures the script continues to wait for successful promise resolution from the publish function.
I've added a `scripts/tsconfig.json` file to use `"module": "ES2022"`, since this permits top-level await.
> fix: Correctly exit publish script

- packages/table-core/src/features/ColumnSizing.ts
Suggested fix for https://github.com/TanStack/table/issues/4483
Allows implementers to provide an alternative document for event listeners to be attached to in relation to the column resize extension. This fixes the use case that a new window has been opened but the table js code is running in the previous window.
> Fix column resize listener document context

- examples/svelte/basic/src/App.svelte
- examples/svelte/basic/tsconfig.json
- examples/svelte/column-groups/src/App.svelte
- examples/svelte/column-groups/tsconfig.json
- examples/svelte/column-ordering/src/App.svelte
- examples/svelte/column-ordering/tsconfig.json
- examples/svelte/column-pinning/src/App.svelte
- examples/svelte/column-pinning/tsconfig.json
- examples/svelte/column-visibility/src/App.svelte
- examples/svelte/column-visibility/tsconfig.json
- examples/svelte/sorting/src/App.svelte
- examples/svelte/sorting/tsconfig.json
Fixes #5279 
Svelte types need to be marked as type imports rather than regular imports
Enabled verbatimModuleSyntax in the svelte examples to detect these errors during development
> docs: Use type imports for svelte examples

- examples/react/editable-data/tsconfig.json
- examples/react/expanding/tsconfig.json
- examples/react/filters/tsconfig.json
- examples/solid/column-ordering/tsconfig.json
Continuation of @lachlancollins' work: https://github.com/TanStack/table/pull/5286
In this follow-up, I have completed the replacement of `tsconfig.json` files eliminating the use of `extends` to resolve local packages across these examples:
- react/editable-data
- react/expanding
- react/filters
- solid/column-ordering 
**Screenshots:**
`react/editable-data` example render issue:
> docs(example): Use tsconfig from create-vite (Part II)

- packages/match-sorter-utils/package.json
- packages/react-table-devtools/package.json
- packages/react-table/package.json
- packages/solid-table/package.json
- packages/svelte-table/package.json
- packages/table-core/package.json
- packages/vue-table/package.json
- Set homepage to link to tanstack.com docs
- Added directory field to repository which points to sub-folder
- Renamed "authors" (invalid) to "contributors" (valid) in match-sorter-utils
- Re-ordered to match other tanstack projects
> fix: Update package.json repository and homepage fields

- docs/guide/column-pinning.md
Fixed wrong link to column-pinning-sticky example. The original link would load the page but the example was not working.
> fix: column-pinning docs wrong link

- docs/installation.md
The `$` sign is currently part of the text copied, so the command fails when pasted in a terminal.
> Remove extra $ in bash commands in installation.md

- docs/config.json
- examples/svelte/filtering/.gitignore
- examples/svelte/filtering/README.md
- examples/svelte/filtering/index.html
- examples/svelte/filtering/package.json
- examples/svelte/filtering/src/App.svelte
- examples/svelte/filtering/src/index.css
- examples/svelte/filtering/src/main.ts
- examples/svelte/filtering/src/makeData.ts
- examples/svelte/filtering/svelte.config.js
- examples/svelte/filtering/tsconfig.json
- examples/svelte/filtering/vite.config.js
I found the regular filtering documentation to be a little dense so wanted to create a stripped down example just for Svelte once I got it working.
> docs: Add svelte filtering example

- examples/vue/row-selection/package.json
Adding a missing dependency for a [Vue Example: Row Selection](https://tanstack.com/table/latest/docs/framework/vue/examples/row-selection)
> Fix: Add missing faker-js dependency for a "Vue Example: Row Selection"

- packages/react-table/__tests__/features/__snapshots__/Visibility.test.tsx.snap
- packages/table-core/src/features/Visibility.ts
This allows `column.getIsVisible()` to return an accurate value for group columns. Only Leaf columns ids are storied in the `columnVisibility` state by default. Parent columns will only be visible if at least one of their child columns are visible. (recursive)
> fix: column getIsVisible works for parent group columns

- docs/framework/vue/vue-table.md
In vue you rarely use `tsx` or write functional components. I think it's strange that this function randomly exists here in this context.
> Remove reactism from vue adapter page

- docs/guide/column-ordering.md
- docs/guide/column-pinning.md
- docs/guide/grouping.md
The doc mentions `columnGroupingMode`. I believe it refers to `groupedColumnMode`. Looks like the prop was renamed in some previous versions.
Great library btw, thanks a lot!
> docs: update `columnGroupingMode` to `groupedColumnMode`

- packages/table-core/src/types.ts
Fixes https://github.com/TanStack/table/issues/5444 by exporting the type `AccessorFnColumnDefBase`
Tested by patching to our project. VSCode no longer complains about the type error.
> fix(types): export AccessorFnColumnDefBase

- examples/angular/basic/angular.json
- examples/angular/basic/src/app/app.component.html
- examples/angular/basic/src/app/app.component.ts
- examples/angular/grouping/angular.json
- examples/angular/grouping/src/app/app.component.html
- examples/angular/grouping/src/app/app.component.ts
- examples/angular/row-selection/angular.json
- examples/angular/row-selection/src/app/app.component.html
- examples/angular/row-selection/src/app/app.component.ts
- packages/angular-table/ng-package.json
- packages/angular-table/src/index.ts
- packages/angular-table/src/proxy.ts
This is still a wip implementation of the angular adapter with a mixed approach:
The adapter will always return a `signal` table. This is useful if passed as a component input. That signal change on every state/option change. If a signal has been used within the options, the table object will be updated automatically.
```ts
@Component({
selector: 'app-root',
standalone: true,
imports: [FilterComponent, FlexRenderDirective],
template : `
<table>
<thead>
@for (headerGroup of table().getHeaderGroups(); track headerGroup.id) {
<tr>
@for (header of headerGroup.headers; track header.id) {
...
}
</tr>
}
</thead>
<tbody>
@for (row of table().getRowModel().rows; track row.id) {
...
}
</tbody>
</table>
`,
styleUrl: './app.component.scss',
})
export class AppComponent {
readonly data = signal([]); …
```
> feat(angular-table): angular adapter implementation with signals

- packages/table-core/src/columnHelper.ts
Fixes https://github.com/TanStack/table/issues/5423
Updates return type of the columns created by
- ColumnHelper.accessor to AccessorFnColumnDef or AccessorKeyColumnDef
- ColumnHelper.display to DisplayColumnDef
- ColumnHelper.group to GroupColumnDef
> fix(table-core): narrow types for columns created by ColumnHelper

- docs/api/features/sorting.md
- docs/guide/sorting.md
- examples/react/pagination/src/main.tsx
- examples/react/sorting/src/main.tsx
- examples/react/sorting/src/makeData.ts
- packages/table-core/src/features/RowSorting.ts
- packages/table-core/src/utils/getSortedRowModel.ts
This pr gives new "official" options to force undefined column values to either the bottom or top rows of a table when a sort is performed on those columns when the `sortUndefined` is set to `'last'` or `'first'` in the column option.
This used to be behavior out of the box with `sortUndefined: 1`, but was changed 10 months ago to not count undefined values. This PR will not have any breaking changes, but will allow those who preferred the old behavior more with an explicit option.
> feat: new sortUndefined last and first options

- docs/guide/sorting.md
The `sortUndefined` option does not handle other nullish values like `null`.
Only `undefined` is sorted by this option, the description might need some update.
> fix(docs): Remove `nullish` in guide of `sortUndefined`

- packages/solid-table/src/index.tsx
`flexRender` param types were taking `any`.
Adding some templating to provide better inference.
> fix(solid-table): flexRender types

- docs/guide/migrating.md
[# Fixing broken doc pages](https://github.com/TanStack/tanstack.com/issues/213)
After the introduction of Shiki code Highlighter in [tanstack.com](https://github.com/TanStack/tanstack.com) docs all the pages which contain `diff` in markdown files are breaking. I have already raised the [PR](https://github.com/TanStack/tanstack.com/pull/214) on that doc repo to render these changes by using `transformerNotationDiff`
> fix: docs pages are breaking due to diff in markdown

- docs/guide/global-filtering.md
The URL pointed to `/examples/filters` which didn't actually include any code involving a global fuzzy filter. This PR simply changes the documentation URL to point to `/examples/filters-fuzzy` which does include a global fuzzy filter example.
> Fix `filters-fuzzy` Documentation Example URL

- examples/angular/grouping/src/app/app.component.ts
- packages/angular-table/src/index.ts
Following are the changes:
- Added optional `injector` parameter for more flexibility. Consumer can `createAngularTable` anywhere.
- Replace runInInjectionContext with an injector in the `effect`.  This has the same behaviour since only `effect` requires to be in the injector context.
- Remove unncessary untracked and signals.
- Remove proxifyTable as I think this is unncessary, since table is not required to be a signal. `laziInit` already proxified the table object. Pls correct me if I'm wrong.
- Refactored grouping example to include pagination  state.
> feat(angular-table): added injector optional parameter for more flexibility

- docs/framework/angular/guide/table-state.md
I've updated the table state docs according to the angular implementation. 
I had to refactor a bit the example of the `Individual Controlled State` combining rxjs and signals instead of using `angular-query`, but I'm not sure about that. It's certainly a good way to make Angular Query known, but at the moment it's a library with the experimental flag. I didn't have any issue using it but I don't know if everything is clear to a user who sees this documentation 
I would like to get also some feedback from @merto20 about my `fully controlled state` approach, which in my opinion could differ from other implementations due to some constraints.
This is what the other frameworks does:
```jsx
const table = createSolidTable({
columns,
get data() {
return data()
},
//... Note: `state` values are …
```
> docs(angular-table) Angular table state docs

- .gitignore
- examples/angular/basic/.devcontainer/devcontainer.json
- examples/angular/column-ordering/.devcontainer/devcontainer.json
- examples/angular/column-pinning-sticky/.devcontainer/devcontainer.json
- examples/angular/column-pinning/.devcontainer/devcontainer.json
- examples/angular/column-visibility/.devcontainer/devcontainer.json
- examples/angular/filters/.devcontainer/devcontainer.json
- examples/angular/grouping/.devcontainer/devcontainer.json
- examples/angular/row-selection/.devcontainer/devcontainer.json
- examples/angular/signal-input/.devcontainer/devcontainer.json
- package.json
- packages/angular-table/package.json
- pnpm-lock.yaml
- tslib should be a dependency, see https://angular.io/guide/angular-package-format#tslib
- ng-packagr as dev dependency of angular package as in Query. We try to keep dependencies local where applicable
- copied .devcontainer.json files from TanStack Query to Angular examples so that they are run as webcontainer on Code Sandbox. Angular CLI works more reliable in dev / web containers.
> Angular examples and dependencies improvements

- docs/framework/angular/angular-table.md
Hey there, in this PR i'm adding some documentation about rendering cell/header/footer content via FlexRender.
In addition to to render strings, we can also render TemplateRefs and Components, which is the corrispective of using a react jsx component into the cell. Hope everything is clear
> docs(angular-table): Add documentation for FlexRenderDirective

- docs/guide/column-defs.md
> docs: Fix `Columns Definitions Guide` example code

- packages/angular-table/src/flex-render.ts
@KevinVandy grouping example was broken due to flexRenderDirective not handling null content (e.g. when a cell is grouped)
Here a screenshot of the grouping example after the fix
> fix(angular-table): handle null and number values with flex-render

- docs/guide/tables.md
Came across this while reading the docs earlier and thought I'd put up a quick fix. Thanks!
> Small typo in documentation regarding column definitions

- examples/lit/column-sizing/src/main.ts
- examples/react/column-sizing/src/main.tsx
For React example - remove unused `setData` (state can be removed entirely if feels like it)
For Lit - print column sizing state instead of weird `123`
> docs: minor fix to lit & react `column-sizing` examples

- examples/react/column-resizing-performant/src/main.tsx
- There is a missing value in useMemo dependency in the example code, so a bug occurs when execute resetSize.
-  AS IS
https://github.com/TanStack/table/assets/57904979/a6899db4-6d54-445d-a9e5-0b0678d13595
- To Be
https://github.com/TanStack/table/assets/57904979/fbed418a-ba0b-4f75-9984-4656092ce1f8
> fix: add dependency because columnSizeVars does not change

- docs/guide/pagination.md
Hey! I was confused by the `autoResetPageIndex` explanation since I noticed it wasn't working on a table with `manualPagination` (which is the expected behavior - all good here).
The docs mention `autoResetPageIndex` is true by default but I had a look at the code and if I'm not mistaken it is undefined by default.
Here is when the magic happens:
https://github.com/TanStack/table/blob/f7e69bc9939d170a1e2fa4112e369814143b8114/packages/table-core/src/features/RowPagination.ts#L226-L230
I rephrased that sentence in the docs removing the mention to "the flag true by default". The _behaviour_ is active by default, but the _flag_ isn't true otherwise `manualPagination` wouldn't override it in the snippet above.
> docs(pagination): rephrase autoResetPageIndex behaviour

- docs/api/core/header-group.md
[In CORE APIS  > Header Group](https://tanstack.com/table/v8/docs/api/core/header-group), the Link to `Header` is broken and rendering a 404 page:
https://github.com/TanStack/table/assets/22207414/93b306fb-aa82-4429-a615-759907a12a9d
> docs: fix Header link in Header Group API

- docs/framework/svelte/guide/table-state.md
- docs/framework/svelte/svelte-table.md
Updates the documentation for compatibility with the new Svelte 5 adapter, which uses runes.
In addition to updating code examples within the docs, I also added a chunk of content in the "Svelte Table Adapter" doc in order to clarify rendering components.
Much of the code examples in the state docs were derived heavily from the `solid-table` docs.
As always, feedback welcome.
> feat: update svelte-table docs for Svelte 5

- docs/framework/react/guide/table-state.md
- docs/guide/column-filtering.md
I was going through the docs to learn how to implement the table features, I found a couple of duplicate words, thought this PR might be helpful!
> docs: Remove duplicate words

- docs/api/core/table.md
Fixed the example link for editable data; it was broken here -  https://tanstack.com/table/latest/docs/api/core/table#meta
Before: 
https://github.com/TanStack/table/assets/33326988/95f85dd4-986c-48f9-999b-355f3af713dd
After: 
https://github.com/TanStack/table/assets/33326988/f4090a36-e571-49ef-9223-51947ff40ebc
> docs: table fix editable example link

- packages/table-core/src/core/headers/CreateHeader.ts
- packages/table-core/src/core/headers/Headers.ts
- packages/table-core/src/core/headers/Headers.types.ts
- packages/table-core/src/core/headers/Headers.utils.ts
- packages/table-core/src/core/headers/buildHeaderGroups.ts
- packages/table-core/src/core/table/Table.ts
- packages/table-core/src/core/table/Table.types.ts
- packages/table-core/src/features/column-pinning/ColumnPinning.ts
- packages/table-core/src/index.ts
- packages/table-core/src/types.ts
- Refactored the headers folder in core for create, base, types, and utils
- Refactored core table folder to separate types and base
- Match file import ordering in index
Questions: Should the ...core/Table.ts file be called CreateTable.ts to match the other core folders that are creating?
> Refactored the core headers/table folders to the new format with separated concerns

- examples/lit/virtualized-rows/package.json
- examples/lit/virtualized-rows/src/main.ts
- examples/lit/virtualized-rows/tsconfig.json
- pnpm-lock.yaml
Now as `@tanstack/lit-virtual` is officially released, using it for the row virtualizer Lit example, as mentioned here - https://github.com/TanStack/table/pull/5599
> docs: use @tanstack/lit-virtual for the virtualized table example

- nx.json
- packages/table-core/src/utils/getGroupedRowModel.ts
Fixes https://github.com/TanStack/table/issues/4881
And Fixes https://github.com/TanStack/table/pull/4882
> fix(getGroupedRowModel): assign/unassign parentId 

- docs/framework/angular/angular-table.md
Shikijs supports [TypeScript](https://github.com/shikijs/textmate-grammars-themes/blob/main/packages/tm-grammars/grammars/angular-ts.json) and [HTML](https://github.com/shikijs/textmate-grammars-themes/blob/main/packages/tm-grammars/grammars/angular-html.json) dialects, which improves the syntax highlighting for the Angular samples.
> docs: update the syntax highlighting for angular

- packages/match-sorter-utils/src/index.ts
The JSDoc comment for the function `rankItem` currently includes the parameter `keys`, although the function does not have a parameter `keys`.
> Fix JSDoc comment for rankItem

- docs/guide/columns.md
Fix a typo in the `columns.md` file.
> Fix typo in documentation

- docs/framework/angular/guide/table-state.md
`SortingState` is an array, so use of `SortingState[]` is incorrect in this example.
> docs: fix incorrect type usage in `@tanstack/angular-table` state documentation

- docs/guide/tables.md
Hello amazing team behind this amazing lib 😄,
A small typo PR change on [docs](https://tanstack.com/table/latest/docs/guide/tables#creating-a-table-instance:~:text=If%20using%20TypeScript%2C%20the%20the%20type%20that%20you%20give%20your%20data%20will%20be%20used%20as%20a%20TData%20generic.%20See%20the%20Data%20Guide%20for%20more%20info.) in the line "If using Typescript..". 
"The" is repeated twice.
Again, thank you so much folks for this library which makes working with tables much much simpler. Cheers.
> fix typo on tables.md

- docs/guide/sorting.md
Updating the instruction in the [sorting guide](https://tanstack.com/table/v8/docs/guide/sorting#multi-sorting)
I think the option to control multi-sorting behaviour should be `enableMultiSort` instead of `enableMultiSorting`
The doc uses `enableMultiSorting`
while the correct [api](https://tanstack.com/table/v8/docs/api/features/sorting#enablemultisort) is `enableMultiSort`
> docs: typo in multi-sorting guide

- README.md
The adapter links in the README.md all result in 404 Not Found. This PR updates them to lead to their corresponding pages under the "getting started" section of the docs.
> docs: update broken links in README

- packages/table-core/src/utils/getFacetedMinMaxValues.ts
I noticed a bug in getFacetedMinMaxValues that I'm surprised no one else has reported or the type checks haven't flagged. Actually, I'm sure I've run into this issue before, but I guess I never got around to reporting it...
The `getUniqueValues` function says it returns (and in testing, does return) an array of values. Thus, `firstValue` becomes e.g. `[123]`, and  `facetedMinMaxValues` will get initialized to `[[123], [123]]`, which sometimes results in the function returning e.g. `[123, [123]]`, depending on the row values. I'm guessing people don't always notice a bug here because an array is being `<`/`>` compared to a numbe, which I think coerces the array to a string?
My first commit makes the minimal change that I think fixes the issue. The second commit reworks the function to be a …
> Fix getFacetedMinMaxValues

- docs/guide/tables.md
Just a tiny docs fix. "Row Models Guide" link in the docs/guide/tables.md was pointing to wrong path.
> chore: fix link to row-models doc in guide/tables.md

- packages/vue-table/src/index.ts
Further improves reactivity for data in the Vue-adapter, which was introduced in #5687.
It mostly fixes some bugs and makes the reactivity more stable and simple. Also fixes a bug which would occur if initial `ref`-data was empty.
> fix: improve reactivity for data in Vue-adapter

- docs/guide/tables.md
A simple fix for incorrect link on `https://tanstack.com/table/latest/docs/guide/tables` page.
> fix: correct broken link to row models section in table guide

- packages/vue-table/src/index.ts
The `mergeOptions` causes huge performance issues in the Vue-adapter whenever the state of the table is updated. This is probably because it merges proxies within proxies, within proxies etc.
As far as I know, there is no need for any special handling of option-merging in the Vue-adapter. Removing it fixes the problem, and the library works like it should.
> fix: major performance bug in Vue-adapter

- packages/vue-table/src/index.ts
First, I just want to say I'm sorry for the inconvenience with the bugs introduced as part of my attempt to make reactivity-support in the Vue-adapter 😇 
Hopefully this PR will fix all the issues that has been reported. This PR will fix the following:
- Make reactivit-support a _non-breaking change_. If a `ref` is not being used, the behaviour should be 100% like before
- Fix a bug where the old way (using `get`) did not work
- Use `shallowRef` for increased performance when using reactivity
I have tested both the old method (`get`) and new method (reactivity) locally, and everything _should_ be OK now.
Fixes #5701
Should also address the issue mentioned by @9mm here: https://github.com/TanStack/table/pull/5687#issuecomment-2276894591
> fix(vue): make normal JS-getters work, make reactivity a non-breaking change

- docs/framework/vue/guide/table-state.md
This PR will add some more information about the use of `shallowRef` in the Vue-adapter. It will also provide an example on what _does_ work and _does not_ work.
> docs(vue): add information about `shallowRef` for reactive data

- packages/table-core/src/filterFns.ts
Fixes https://github.com/TanStack/table/issues/4280
When searching for a number, seeing a TypeError: filterValue.toLowerCase is not a function.
The
[toLowerCase()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase)
method does not exist on the Number prototype but does on the String prototype.
Converting it to a string before calling .toLowerCase method.
> Bug fix - allow searching of numbers in global filters

- docs/config.json
Just a small typo fix for the sidebar in the docs.
> Fix label typo in config.json

- packages/solid-table/src/createTable.ts
Reintroduce the `mergeOptions` property which is needed to merge props without losing reactivity when calling `setOptions`
> Fix solid adapter in alpha version

- packages/react-table/src/index.tsx
The JSX Global namespace has been deprecated for a while, and removed in React 19: https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript
> Global JSX namespace is deprecated

- examples/react/kitchen-sink/src/components/ActionButtons.tsx
This fixes the issue of the kitchen sink example not loading locally/on Stackblitz/CodeSandbox since table is not defined in that scope anymore.
Related Issue: https://github.com/TanStack/table/issues/5732
> fix: Use correct pagecount accessor (#5732)

- examples/react/virtualized-infinite-scrolling/src/main.tsx
In this case, it will accomplish the same functionality without the type casting
> Change `target` to `currentTarget` in the example

- examples/lit/sorting-dynamic-data/.gitignore
- examples/lit/sorting-dynamic-data/README.md
- examples/lit/sorting-dynamic-data/index.html
- examples/lit/sorting-dynamic-data/package.json
- examples/lit/sorting-dynamic-data/src/main.ts
- examples/lit/sorting-dynamic-data/src/makeData.ts
- examples/lit/sorting-dynamic-data/tsconfig.json
- examples/lit/sorting-dynamic-data/vite.config.js
- packages/lit-table/src/index.ts
this fixes an issue I discussed in discord where with the lit table 
adapter, updating a data array did not get reflected by the table.
It is a one-line change to the TableController, and a new example that demonstrates the difference.
> fix dynamic data updates in the Lit Table Adapter

- packages/lit-table/src/index.ts
Currently the Lit adapter takes only `columns`, `data` and `state` into account when updating the table options.
This PR spreads the options, as suggested in this [issue](https://github.com/TanStack/table/issues/5831).
> fix: spread table options in lit adapter

- packages/table-core/src/filterFns.ts
The `filterValue` for this function is not an array. Therefore, we should not check for its length.
> Fix `arrIncludes` filterFn

- packages/table-core/src/features/ColumnSizing.ts
- packages/table-core/src/utils/document.ts
- packages/table-core/tests/test-setup.ts
- packages/table-core/tests/utils/document.test.ts
- packages/table-core/vitest.config.ts
Related to my comment https://github.com/TanStack/table/pull/5747#issuecomment-2799893027
I'd consider to remove jsdom env in table-core test since since this package should be framework agnostic. It could ensure us that things doesn't break while running the code in a non browser env. wdyt?
I've added two new utils safelyAccessDocument and safelyAccessDocumentEvent just for testing purposes (actually using only `safelyAccessDocument`) as it can be useful to reuse that portion of code also in other files. Those utils are not currently present in public api, is it ok?
> fix(table-core): use right Document instance on getResizeHandler (column-sizing feature)

- examples/react/query-router-search-params/src/hooks/useFilters.ts
This PR fixes a Typescript problem with the `navigate` function in the `useFilters` hook.
Fixes #5812
> fix(examples): add `to` to navigate to fix typescript

- packages/svelte-table/src/createTable.svelte.ts
In svelte 5, $state (here, the variable named 'state')  referenced locally is not reactive, because of how evaluation occurs[1].
This means in the listed code, ...state will only ever refer to the original value of state, even if it is later updated or re-evaluated (by updateOptions, for example)
To make it reactive locally, the docs recommend using a closure (you can use getter functions and properties too if you want), which is what we do here.
This makes it so ...state always refers to the current value of state, even after updateOptions changes it..
This in turn, fixes the browser warning issued by svelte on all usage of createTable.
See https://svelte.dev/docs/svelte/compiler-warnings#state_referenced_locally for more details.
Svelte (currently) only warns if you do this and *also* …
> Don't directly reference local state

- examples/react/virtualized-rows-experimental/src/main.tsx
Table is broken when virtualRowIndex is equal to 0
> Fix if statement in Virtualized Rows (Experimental)
