README.md
src/index.js
src/pagination.js

Now you can customize the Text for the Pagination in 'Page 1 of X', also in the rows Dropdown.

Added props for more pagination customization

---

src/index.js

added missing named export for ReactTableDefaults

---

src/index.js

Pass relevant attributes to footer JSX

---

src/pagination.js

removed form tag from pagination component to avoid nested forms error

---

src/pagination.js

connected to #114
Sorry notice that after last PR was already merged.

use button type button in pagination to prevent form submitting if using inside of the form

---

.storybook/config.js
src/lifecycle.js
stories/ControlledTable.js

* Previously existing props would overwrite passed in state
* Now passed in state gets precedence

Change precedence in 'getResolvedState'

---

stories/CellRenderers.js
stories/ControlledTable.js
stories/Footers.js
stories/Simple.js

There were some differences between the actual code and the code highlight, particularly important on `Footers.js`

Fix storybook code highlight

---

.storybook/config.js
README.md
src/defaultProps.js
src/index.js
src/methods.js
stories/CustomExpanderPosition.js
stories/PivotingOptions.js

Enhance the `expander` column option to support most column features for Expander Columns and Pivot Columns.
Allows full control over positioning and rendering Expander Columns and Pivot Columns.
Update `Custom Expander Position` story.
Add `Pivoting Options` story.

Enhanced expander and pivot

---

CHANGELOG.md
README.md
src/defaultProps.js
src/index.js
src/index.styl
src/methods.js
stories/PivotingOptions.js

Allow pivot columns to keep their individual column options for headers, filters, and footers.
Allows filtering on all of the column in the pivot.

Enhance pivots

---

src/defaultProps.js

Fix comparing rows with strings and null values.
Fix checking if type is string.

Fix default sort algorithm

---

src/index.styl

should resolve the issue with loading overlay in IE10

fix for issue #240

---

README.md

Tiny wording update in README.

Update README for filterRender naming update

---

package.json
src/index.js
src/propTypes.js
yarn.lock

**What Changed**
1. Added the `prop-types` library as a `devDependency`.
2. Added a file containing all the `propType` definitions.
2. Added `proptypes` as a static variable of the `ReactTable` class.
**Related Issues**
#549 ~ Add PropTypes to React-Table

Add the PropTypes node module

---

README.md

https://www.npmjs.com/package/react-table
( Assuming this is still maintained it would be nice to have this a visible option for instal on this repo for those of us that use npm over yarn. )

Update README.md to include npm as option for installing. 

---

src/index.js

Pass the column to `getResizerProps` callback
Solves https://github.com/react-tools/react-table/issues/666

Add column to getResizerProps

---

src/defaultProps.js
src/index.js
src/lifecycle.js

This closes #676 and closes #701

Add defaultPage prop

---

src/hoc/foldableTable/index.js
src/hoc/selectTable/index.js
yarn.lock

disable linter on the foldablehoc and add option to position checkbox column on the right or the left

fix linter , update selectTable hoc

---

package.json
src/defaultProps.js

Wanted ability to specify custom placeholder values in the column declaration.

Added placeholder to filter input.

---

src/hoc/treeTable/index.js

Hi,
in our project we noticed that treeTable has missing ARIA role. Regular table has it, but probably it was omitted in treeTable. That causes issue in axe validation tools.
So I'm raising small PR :)

Accesibility improvement - add role to tr in treeTable

---

README.md
src/defaultProps.js
src/pagination.js
src/propTypes.js

This is a small change to add an 'aria-label' attribute to the page jump input and the page row count selector. It adds a prop for each so that custom text can be passed in for the label

Pagination accessibility

---

docs/src/examples/expander/index.js
src/index.js

I needed a way to close the expanded component from within the component so added a callback to the subComponent arguments.

Add callback to subComponent for child components to close itself

---

docs/src/App.js
package.json

Fixing the sandbox code issue. However, the foldable folder is not found in the 6.8.6 npm package. I'm not sure why because the foldable table still found in lib folder when running npm run build command.

fixed the sanbox code issue

---

package-lock.json
src/hoc/selectTable/index.js

Adding IDs for select table, fixing backwards compatibility on floating left checkbox

---

src/index.js

I use styled-components and custom pagination component on top and bottom of the table. Pagination component has a bit different style on top of the table and I need to differentiate in styled component if pagination is on top or bottom. It would be nice to add a prop `isTop` into pagination component to support this use case.

adding position prop into pagination component

---

src/index.js
src/methods.js
src/propTypes.js

There were a few lint issues on `master`. I fixed the ones I could; one remains but I'm not sure what the fix is. the `cellInfo` variable is out of scope where it is used.

cleanup all but one linting issue

---

src/index.js
src/methods.js
src/utils.js

Revert Support for recursive Header Groups https://github.com/tannerlinsley/react-table/pull/1241
Causing bugs https://github.com/tannerlinsley/react-table/issues/1243
and https://github.com/tannerlinsley/react-table/issues/1248

revert 3baa7139fbb5cf5f706ec228036b0e2eac806113

---

src/methods.js

fix https://github.com/tannerlinsley/react-table/issues/1257

fix typo in methods.js

---

src/index.js
src/methods.js

Clean up revert

---

src/index.js
src/methods.js

Solved the "resize column bug" when no "minResizeWidth" is  specified
The bug in action here (try resize a column): 
https://codesandbox.io/s/50m2okv80x

BUG in resize columns

---

src/methods.js

Fix #1275 minResizeWidth not working when using functional accessor

---

README.md

Resolve issue #1320

---

src/methods.js

Must be a typo, the prop is `filtered` not `filter`.

Fix initial state in fireFetchData

---

.eslintrc
package.json
src/hooks/useColumns.js
src/hooks/useExpanded.js
src/hooks/useFilters.js
src/hooks/useGroupBy.js
src/hooks/usePagination.js
src/hooks/useRows.js

They all seemed like reasonable warnings, this squashes them.

Fix lint errors from react-hooks/exhaustive-deps

---

README.md

Fix deprecated getThProps function in doc

---

src/utils.js

I have a data source where for some rows I don't have a property define in columns.

Avoid react error if the data source doesn't have the property.

---

README.md
examples/editable-data/README.md
examples/expanding/README.md
examples/filtering/README.md
examples/grouping/README.md
examples/pagination-controlled/README.md
examples/pagination/README.md
examples/row-selection/README.md
examples/sorting/README.md
examples/sub-components/README.md

Here's the fix on your main readme! Also updated the sub readmes with the correct links.
references https://github.com/tannerlinsley/react-table/issues/1436

updating code sandbox links in example README and main README

---

src/plugin-hooks/useSortBy.js

it improves performance because cuts a lot of sorting manipulations on empty arrays.

improve(sort): don't sort subrows less than 2 items

---

src/hooks/useTable.js
src/hooks/useTableState.js
src/plugin-hooks/useExpanded.js
src/plugin-hooks/useFilters.js
src/plugin-hooks/useGroupBy.js
src/plugin-hooks/usePagination.js
src/plugin-hooks/useRowState.js
src/plugin-hooks/useSortBy.js

Only count visible columns for determining the colSpan
fix #1446

Fix #1446: Only count visible columns for determining the colSpan

---

docs/api.md
examples/sorting/README.md

Added an example and the column sortType options.

Changed docs to include sortType options for useSortBy

---

src/utils.js

Fixes https://github.com/tannerlinsley/react-table/issues/1336 (or at least fixes my issue with double click not working)

Fix 6.10 remounting/double click issue

---

examples/absolute-layout/src/App.js

Refactor get rid of statement return and add index for protect re render

Refactor code

---

examples/absolute-layout/src/App.js
examples/animated-framer-motion/src/App.js
examples/basic/src/App.js
examples/block-layout/src/App.js
examples/column-ordering/src/App.js
examples/column-resizing/src/App.js
examples/editable-data/src/App.js
examples/expanding/src/App.js
examples/filtering/src/App.js
examples/grouping/src/App.js
examples/kitchen-sink-controlled/src/App.js
examples/kitchen-sink/src/App.js
examples/material-UI-components/src/App.js
examples/pagination-controlled/src/App.js
examples/pagination/src/App.js
examples/row-selection/src/App.js
examples/sorting/README.md
examples/sorting/src/App.js
examples/sub-components/src/App.js

Updated previous PR to use a function call & return statement
Previous PR for reference: [link](https://github.com/tannerlinsley/react-table/pull/1629)

Update syntax in examples

---

package.json

Oops, forgot to put the definition file into the list of included files inside a package :)

Added index.d.ts to the package.json

---

src/plugin-hooks/useExpanded.js
src/plugin-hooks/useRowSelect.js

* This one also is listening to rows instead of data.
(Finally) Fixes #1657

Fix default resetSelectedRowsDeps

---

CHANGELOG.md
src/plugin-hooks/useRowState.js

Fix issue with missing columnId in updater on column spread

---

src/index.js
src/lifecycle.js

ok another attempt at this 😄
I tested the changes locally (with some simple cases) and haven't noticed any issues.
if you are available @tannerlinsley  could you confirm if this works for your test cases? I tried to build the docs but it seems they are simply embedding some outdated codesanbox urls. 
thanks!

[v6] Removes unsafe lifecycle method

---

.size-snapshot.json
examples/column-resizing/src/App.js
src/plugin-hooks/useResizeColumns.js

.add onTouchStart to mergeProps
.add touch-action css to resizer
.mod increase resizer width or it is very hard to activate using touch devices

.add touch events to useResizeColumns

---

.size-snapshot.json
docs/api/useGlobalFilter.md
src/plugin-hooks/useGlobalFilter.js

Wrapped setGlobalFilter in useCallback. Minor doc fix in useGlobalFilter.md

misc fixes for useGlobalFilter

---

docs/api/README.md

* or just a reminder. Please obliterate at your will

Minor contribution on line 58

---

examples/full-width-resizable-table/package.json
examples/full-width-resizable-table/src/App.js
examples/full-width-resizable-table/yarn.lock
src/hooks/useTable.js
src/plugin-hooks/useFlexLayout.js

*  Allow useFlexLayout to honor canResize by calculating flex width separately from total width.
*  Update example to show the selection checkbox since that's a common fixed width use case.
*  Add example for right aligning columns.
*  Tweaked the styles for the table to better align the resize handles (since it made verifying the rest easier when they weren't misaligned by the scroll bar width)
Note that the resize behavior is still rather strange, but that's a separate problem that this change didn't really effect.

Add fixed width column support to useFlexLayout

---

.size-snapshot.json
docs/api/usePagination.md
src/plugin-hooks/usePagination.js

autoReset pageIndex on globalFilter change
fix #1812

fix(usePagination resetPage on globalFilter change): pageIndex reset

---

docs/api/useSortBy.md

Added new parameter in useSort details - https://github.com/tannerlinsley/react-table/pull/1615

Doc for https://github.com/tannerlinsley/react-table/pull/1615

---

docs/api/useFilters.md

Simple documentation about how to use the setAllFilters function.

Improves setAllFilters documentation

---

docs/api/useTable.md
src/hooks/useColumnVisibility.js

fix(usecolumnvisibility): trigger resetHiddenColumns on columns change

---

examples/row-dnd/package.json

To Address #1923 
+ Prevents code sandbox from crashing the dnd example

Updated react-dnd package

---

src/filterTypes.js

The includes was buggy and was looking the opposite way around. It needs to look if the filterValue is included in the rowValue.

Fixed includes filter

---

docs/api/useFilters.md

Path just needed to back up ./ to ../

Fix FAQ path in useFilters.md

---

src/plugin-hooks/usePagination.js

fix: manualPagination does not work with pageCount -1

---

docs/api/useBlockLayout.md

No mis-casings found anywhere else in the api docs

Fix case on useBlock(L)ayout

---

src/plugin-hooks/useGroupBy.js

[groupBy] fix typo on aggregateValue

---

package.json

- Update homepage url for listing on npm js page
- Removing not needed and unavailable file from package (types file, it seems earlier it was supposed to be provided with package only, now it is been provided through DT)

Update homepage url for listing on npm js page

---

docs/api/README.md
docs/api/useAbsoluteLayout.md
docs/api/useBlockLayout.md
docs/api/useExpanded.md
docs/api/useFilters.md
docs/api/useFlexLayout.md
docs/api/useGlobalFilter.md
docs/api/usePagination.md
docs/api/useResizeColumns.md
docs/api/useRowSelect.md
docs/api/useRowState.md
docs/api/useSortBy.md
docs/api/useTable.md
docs/concepts.md
docs/examples.mdx
docs/installation.md
docs/quickstart.mdx

Seems like this was caused by Docz #2013.

fixed lots of links in the docs

---

docs/api/useTable.md

complete docs for overriding Cell renderer

---

src/plugins/withColumnResizing.js
src/utils.js

Apply #2325 to the next version work.

[Next] fix: detect browser support for passive events

---

docs/api/useTable.md

I was really confused on how to toggle hide and show columns. This was the missing documentation I needed.

Clarify how to update hiddenColumns

---

docs/quickstart.md

Two import statements intended to be part a code block were outside of the markdown.

Moved import statements to code block

---

docs/src/components/LayoutDocs.js

docs: fix incorrect active nav link

---

examples/column-resizing/src/App.js
src/plugin-hooks/useResizeColumns.js
src/utils.js

Added functionality for resetting column resized width to the initial width

feat(useResizeColumns): add reset column resizing

---

docs/src/components/Nav.js
docs/src/components/Search.js
docs/src/components/Sidebar.js
docs/src/components/useSearch.js
docs/src/pages/_app.js

Same changes as I applied to the react-query docs in https://github.com/tannerlinsley/react-query/pull/773

docs: refactor search modal

---

docs/src/pages/docs/quick-start.md

docs: fix typo

---

src/utils.js

This will be helpful to add more meta data to headers, when calling headerGroups formation.

feat(headerGroups): add meta data to header via callback

---

src/plugin-hooks/usePagination.js

fixes: https://github.com/tannerlinsley/react-table/issues/2484

fix: goToPage method

---

src/plugin-hooks/useGroupBy.js

Can be useful to set groupBy state directly from instance

feat(useGroupBy): Set groupBy state via method

---

docs/src/manifests/manifest.json

docs(useExpanded): Add sub-comp-lazy to sidebar

---

src/aggregations.js

Handle negative number usecase in aggregation for min, max and minMax type

fix(aggregations): min, max agg -ve num handling

---

docs/src/pages/docs/examples/row-selection-and-pagination.md

fix: CodeSandbox and Source link

---

examples/virtualized-rows/src/App.js
examples/virtualized-rows/src/scrollbarWidth.js

width of FixedSizeList take into account the width of  scrollbar
#2709

fix(virtualized-rows): header/body column aligment

---

src/plugin-hooks/useRowSelect.js

Fix: 
- https://github.com/tannerlinsley/react-table/issues/2659
- https://github.com/tannerlinsley/react-table/issues/2171

fix(useRowSelect): verify row selection based on reducer state

---

src/plugin-hooks/tests/useFilters.test.js

As mentioned in #2519 
There was no bug, everything is fine.
Added a test to ensure custom filters are properly called and reset on undefined, not on any false value.

test(useFilters): Test custom filters

---

src/utils.js

* Add recently removed export statement (via https://github.com/tannerlinsley/react-table/pull/2738)
* Remove log statements

fix(utils): Add recently removed export statement

---

examples/sorting/README.md

Remove extra backticks from last diff example.

docs: Update README.md for sorting example

---

package.json

fix(deps): add support for React 17

---

docs/src/pages/index.js

Fixing a small typo on the home page.

docs(home-page): fix typo

---

docs/src/pages/docs/api/overview.md

see https://lineup-lite.netlify.app for documentation and details.

docs: add link to LineUp-lite

---

package.json
yarn.lock

Allow React 18 on v7 and test against it.

chore(deps): allow React 18

---

docs/api/column-ordering.md
docs/api/column-pinning.md
docs/api/filters.md
docs/api/row-selection.md

docs updates to reflect resetState changes from last week

update docs for resetState changes

---

docs/api/features/sorting.md
packages/table-core/src/features/Sorting.ts

Add getNextSortingOrder to resolve the discussion in #3944

Add getNextSortingOrder to sorting column api

---

docs/guide/filters.md

Current url leads to error page

Filters API url adjustment

---

docs/guide/09-features.md

This will fix some absolute paths in docs.
great job on v8! :rocket:

Fix absolute paths on features.md

---

docs/api/features/sorting.md

Fixed wrong function declaration for Custom Sorting Functions to align with the Source Code Declaration.

Fixed wrong function declaration for Custom Sorting Functions

---

docs/guide/04-column-defs.md

I was just reading through the docs and found a few typos. Great docs. 
I'm in the business of making headless UI myself (I've written a Tree Component: https://github.com/brimdata/react-arborist and I'm working on a JSON Inspector component.). I'm finding it difficult to know how much state to control internally, so I'm looking to your project here for prior art. Thank you!

Correct a few typos

---

examples/react/pagination/src/main.tsx

Multiple Table (react function component, Table from react-table) causing failure to run code.

Fix broken pagination example

---

packages/table-core/src/types.ts

Fixes [#4081](https://github.com/TanStack/table/issues/4081)

refactor: return type of `ColumnDefTemplate`

---

packages/table-core/src/sortingFns.ts

fix: datetime sorting function

---

examples/react/pagination-controlled/src/main.tsx

Fixes #4122. QueryClientProvider was missing.

fix: controlled pagination example 

---

docs/guide/column-defs.md

Link to grouping is broken, this change should fix it based on the computed URL.

Update link to grouping

---

docs/api/core/column-def.md
packages/table-core/src/core/column.ts
packages/table-core/src/types.ts

Based on https://github.com/TanStack/table/discussions/4145

Add generic parameters to ColumnMeta

---

README.md

Checked`full-width-resizable-table` on docs

Update `full-width-resizable-table` on docs

---

examples/react/basic/src/main.tsx
packages/react-table-devtools/src/Explorer.tsx
packages/react-table-devtools/src/styledComponents.ts
packages/react-table-devtools/src/utils.ts
packages/table-core/src/utils.ts

Closes: #4224 
Upstream: #4185

fix: type instantiation is excessively deep

---

docs/api/core/cell.md
docs/api/core/column.md
docs/api/core/header-group.md
docs/api/core/header.md
docs/api/core/row.md
docs/api/core/table.md
docs/guide/column-defs.md

Fixed some link error/404 in docs
And more.

docs: fixed some link error

---

docs/api/features/pagination.md

documentation: fix typo in pagination.md

---

packages/table-core/src/utils/getSortedRowModel.ts

use spread instead of slice

---

packages/table-core/src/columnHelper.ts
packages/table-core/src/core/cell.ts
packages/table-core/src/core/column.ts
packages/table-core/src/core/headers.ts
packages/table-core/src/core/row.ts
packages/table-core/src/core/table.ts
packages/table-core/src/features/ColumnSizing.ts
packages/table-core/src/features/Expanding.ts
packages/table-core/src/features/Filters.ts
packages/table-core/src/features/Grouping.ts
packages/table-core/src/features/Ordering.ts
packages/table-core/src/features/Pagination.ts
packages/table-core/src/features/Pinning.ts
packages/table-core/src/features/RowSelection.ts
packages/table-core/src/features/Sorting.ts
packages/table-core/src/features/Visibility.ts
packages/table-core/src/types.ts
packages/table-core/src/utils.ts

Revert "perf: optimise types"

---

packages/table-core/src/utils/filterRowsUtils.ts

This is regarding: https://github.com/TanStack/table/issues/4190
Unfiltered:
Leaf:
Middle:
Root:

Fix: filterFromLeafRows

---

packages/table-core/src/features/Pagination.ts

Fixes https://github.com/TanStack/table/issues/4271

Don't set pageIndex to -1 when resetting page index with pageCount = 0

---

packages/table-core/src/utils/getSortedRowModel.ts

Fix sorting leafRows when there is one subRow

---

packages/table-core/src/core/cell.ts
packages/table-core/src/core/column.ts
packages/table-core/src/core/headers.ts
packages/table-core/src/core/row.ts
packages/table-core/src/core/table.ts
packages/table-core/src/features/ColumnSizing.ts
packages/table-core/src/features/Expanding.ts
packages/table-core/src/features/Filters.ts
packages/table-core/src/features/Grouping.ts
packages/table-core/src/features/Ordering.ts
packages/table-core/src/features/Pagination.ts
packages/table-core/src/features/Pinning.ts
packages/table-core/src/features/RowSelection.ts
packages/table-core/src/features/Sorting.ts
packages/table-core/src/features/Visibility.ts
packages/table-core/src/types.ts

This PR re-implements much of @terry-au 's #4419  PR. However, it only focusses on the `type` to `interface` conversions

perf: convert types to interfaces

---

docs/api/core/table.md
docs/api/features/pagination.md

docs: autoResetPageIndex docs typo

---

README.md

Add `pnpm` and `yarn` install script definitions

Update README.md: Add pnpm and yarn install scripts

---

packages/vue-table/src/index.ts

Fixes issue with types in FlexRender
#4440

Fixes issue with types in FlexRender

---

packages/table-core/src/features/ColumnSizing.ts

Revert "Fix: onColumnSizingChange does not return correct value when react.strictmode is not used"

---

packages/table-core/src/utils/filterRowsUtils.ts

https://github.com/TanStack/table/issues/4688
It will fix the ts error during the compilation

fix: fix ts compilation error (#4688)

---

packages/table-core/src/aggregationFns.ts
packages/table-core/src/utils.ts

fixes #4582 (median aggregation function)

fix: median aggregation function

---

packages/svelte-table/src/index.ts
packages/svelte-table/src/render-component.ts

closes https://github.com/TanStack/table/issues/4778

fix(svelte): type cast the result of `renderComponent`

---

packages/table-core/src/core/cell.ts
packages/table-core/src/core/column.ts
packages/table-core/src/core/headers.ts
packages/table-core/src/core/row.ts
packages/table-core/src/core/table.ts
packages/table-core/src/features/ColumnSizing.ts
packages/table-core/src/features/Expanding.ts
packages/table-core/src/features/Filters.ts
packages/table-core/src/features/Grouping.ts
packages/table-core/src/features/Ordering.ts
packages/table-core/src/features/Pagination.ts
packages/table-core/src/features/Pinning.ts
packages/table-core/src/features/RowSelection.ts
packages/table-core/src/features/Sorting.ts
packages/table-core/src/features/Visibility.ts

I replaced the Object.assign with direct mutation in create[Row,Cell,Column,Header,Table]. No features were changed, I did minimal touch, tests passed.
Object.assign is very performance Heavy, when compared with direct assignment, and can easily be replaced with direct mutations in the creational functions. Since these get called *a lot* when the data changes, especially with large amounts of data, the performance impact is quite huge. According to my measurements in my application, the performance of calculating or re-calculating the RowModels (this affects all of them) increased between 30%-50%, I measured the performance using the built-in debug features with tables of rowSize 100, 1.000, 10.000, 20.000, 50.000. The improvement becomes noticeable after about a 1,000 rows.
ref on …

Increase core performance by 30%-50% 

---

docs/api/core/table.md

Updated wrong column-defs redirect link

Update table.md column-defs link

---

docs/api/features/sorting.md

See https://github.com/TanStack/table/blob/a1e9732e6fc3446a2ae80db72a1f2b46a5c11e46/packages/table-core/src/sortingFns.ts#L54

fix wrong description in sorting.md

---

packages/table-core/src/columnHelper.ts

RequiredKeys is not used in this file

Delete variables that are not used

---

.github/workflows/ci.yml
.github/workflows/pr.yml
project.json

If these secrets are set, it should "just work"

chore: Attempt to enable Nx cloud caching

---

package.json
pnpm-lock.yaml

See https://github.com/TanStack/config/pull/35

ci: Update example dependencies when publishing

---

examples/react/material-ui-pagination/src/actions.tsx
examples/react/material-ui-pagination/src/main.tsx

Update a TablePagination property from Material UI
https://mui.com/material-ui/api/table-pagination/#table-pagination-prop-SelectProps

docs: updated deprecated prop

---

nx.json

https://nx.dev/ci/recipes/security/access-tokens

ci: Add read-only Nx cloud access token

---

.github/workflows/ci.yml
.github/workflows/pr.yml
.gitignore
.nx/workflows/dynamic-changesets.yaml
nx.json

See here: https://github.com/TanStack/query/pull/6863

ci: Use Nx Agents

---

.gitignore
package.json
pnpm-lock.yaml

- Enables per-project task grouping in Nx cloud agents

ci: Update Nx

---

package.json
packages/solid-table/package.json
packages/solid-table/src/index.tsx
packages/solid-table/tsconfig.build.json
packages/solid-table/vite.config.ts

Fixes compatibility with server-side environments such as SolidStart
See https://github.com/TanStack/form/pull/631

fix(solid-table): Add `solid` export condition

---

packages/table-core/src/core/table.ts
packages/table-core/src/features/column-filtering/ColumnFiltering.ts
packages/table-core/src/features/column-filtering/ColumnFiltering.types.ts
packages/table-core/src/features/column-filtering/ColumnFiltering.utils.ts
packages/table-core/src/filterFns.ts
packages/table-core/src/index.ts
packages/table-core/src/types.ts
packages/table-core/src/utils/getFilteredRowModel.ts

Refactoring ColumnFiltering into folder with separate base, types, and utils.

chore: Refactoring ColumnFiltering into folder with separate base, types, and utils

---

docs/api/features/row-selection.md

Discussion about this problem here https://github.com/TanStack/table/discussions/4780

Clarify that getIsSomeRowsSelected return false if all rows are selected

---

examples/react/editable-data/src/main.tsx
examples/react/expanding/src/main.tsx
examples/react/filters/src/main.tsx
examples/react/full-width-table/src/main.tsx
examples/react/fully-controlled/src/main.tsx
examples/react/grouping/src/main.tsx
examples/react/kitchen-sink/src/components/ActionButtons.tsx
examples/react/pagination-controlled/src/main.tsx
examples/react/pagination/src/main.tsx
examples/react/row-pinning/src/main.tsx
examples/react/row-selection/src/main.tsx

add min and max in "number" input in relative examples. Then the number in input will not less than 1 and greater than max. pages number.

add min and max in "number" input in relative examples.

---

examples/react/kitchen-sink/src/components/ActionButtons.tsx

Fixes unbound `table` error in `ActionButtons.tsx`

fix broken kitchen-sink example (react)

---

docs/guide/columns.md

docs: update columns

---

docs/guide/data.md

Accessor function accepts row object so to access age we should access it from row.

Update data.md: fix bug in example code block
